yomidevs/yomitan

README.md
Add a basic banner at the top to explain what this fork is, its goal, and how people can contact us. Also replace all references to yomichan with yomitan.
=> README.md: yomichan → yomitan; add announcement

.github/workflows/broken-links.yml, .lycheeignore, README.md
This PR:
* Adds link checking in CI for markdown and HTML files using `lychee`
* Fixes all broken links possible
* Does not yet fix the following broken links because they require a dependency update (parse5 v7.1.1 → v7.1.2), which will be done in a separate PR
```
| ✗ [404] https://github.com/inikulin/parse5/blob/v7.1.1/LICENSE | Failed: Network error: Not Found
| ✗ [404] https://github.com/inikulin/parse5/tree/v7.1.1/packages/parse5 | Failed: Network error: Not Found
| ✗ [404] https://github.com/inikulin/parse5/blob/v7.1.1/LICENSE | Failed: Network error: Not Found
```
Note the 4th line in `.lycheeignore` is due to this lychee bug:
* https://github.com/lycheeverse/lychee/issues/986
=> Use `lychee` to check for broken links in CI & fix broken links

dev/data/manifest-variants.json, ext/manifest.json, package.json
* Get rid of old v2 manifests as they will soon be unusable and considerably clutter up the project and currently-in-progress CD
* Rename yomichan to yomitan and update links where applicable within the manifest and package.json
=> Update manifest scripts: only support v3, and yomichan->yomitan

build.sh, shell.nix
* Uses `#!/bin/sh` to improve build script portability
* Adds a `shell.nix` file to provide all necessary dependencies to build the project on [nix](https://nixos.org/)
=> Make it easy to build project on Nix package manager / NixOS

ext/action-popup.html, ext/info.html, ext/issues.html, ext/legal.html, ext/permissions.html, ext/popup-preview.html, ext/popup.html, ext/search.html, ext/template-renderer.html, ext/welcome.html
This mostly completes the work from #97. The license under legal.html is still not changed, and will be covered in a different PR.
=> Renamed most instances of Yomichan -> Yomitan under ext/*.html

ext/js/media/media-util.js
From ctpk:
> By default, if an audio media type does not appear in this switch statement, it gets the ".mp3" file extension. This causes issues with aac files in the iphone anki app.
=> Apply .aac extension so playback works in downstream Anki clients

ext/js/background/backend.js
This PR simply renames `chrome.browserAction` -> `chrome.action`, to support manifest v3.
According to this blog, it seems like this is completely safe to do (because `chrome.action` only adds to the existing api, and doesn't change anything): https://developer.chrome.com/blog/mv3-actions/#manifest-v3-changes
This affects the icon that is shown when no dictionaries are downloaded. With this change, the `!` icon actually shows.
Partially fixes #96.
Original:
Before fix:
After fix:
(Note: the fix works on Firefox as well)
=> fix: renamed chrome.browserAction -> chrome.action

ext/js/accessibility/accessibility-controller.js
As reported by CodeQL:
> This string, which is used as a regular expression , has an unescaped '.' before 'google.com/', so it might match more hosts than expected.
=> Fix Google Docs URL regex to not be excessively wide

ext/data/schemas/options-schema.json, ext/js/core.js, ext/js/pages/settings/backup-controller.js
- `ext/data/schemas/options-schema.json`: renames the default tag added to Anki to `yomitan`.
- `ext/js/pages/settings/backup-controller.js`: changes the name of the exported settings file from `yomichan-settings-(date)` to `yomitan-settings-(date)`.
- `ext/js/core.js`: error message now links to the correct repo
=> More various renaming from Yomichan -> Yomitan

.github/workflows/playwright.yml, .github/workflows/playwright_comment.yml
Background
===
Previously the playwright action would only work from `themoeway/yomitan`-originated branches, not from fork-originated branches. Namely, for PRs from forks, the comment step would fail due to the `GITHUB_TOKEN` not having write permissions. The reason for this security control on GitHub's side is because the code being executed is from the fork and therefore untrusted, so we wouldn't want it to have any write privileges on our repo as it could do something arbitrary.
Reference: [Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Fix
===
This fix splits up the action into two actions:
- `playwright.yml` (which only has read privileges) executes the forked repo's …
=> Fix playwright action so that it leaves comments even for PRs from forks

.github/workflows/playwright.yml
By default CJK fonts are not installed on the Ubuntu image, which led to characters not displaying on the playwright action.
=> playwright: install Japanese font in Ubuntu image

.github/workflows/create-prerelease-on-tag.yml, .github/workflows/publish-firefox-development.yml
It is required to pass the upload_url from the release generation action all the way through the workflow_dispatch to the upload action for the xpi upload to work.
=> fix publish-firefox-development's upload_url for xpi

ext/js/media/audio-system.js
JPod always returns an audio file even for audio misses. Examples of audio misses from JPod are そういう and そう言う. The way Yomitan/Yomichan deals with it is by checking the duration of the audio.
For some reason, the duration changed on Firefox, so this just patches that. Ideally, we would check the hash somehow (like how the batch add audio add-on works), but I couldn't figure out how to do that with some extremely basic googling.
=> fix: JPod default audio duration check on Firefox

.github/workflows/playwright.yml
When playwright is installed (i.e., not pulled from cache), the `--with-deps` flag causes it to pull in system dependencies as well. That makes the current caching strategy incoherent, as those dependencies will not be part of the cache as defined. Causing different behavior when pulling from cache vs installing fresh.
In particular, some of the dependencies it pulls in are fonts, which causes the output of the test to change due to the available fonts changing.
In fact, fonts are the _only_ dependencies it pulls in, everything else is already present in the stock ubuntu image. So it seems fine to just remove `--with-deps` and just pull in the image. If we discover we need system deps at any point, we can use `npx playwright install-deps chromium` in a separate command to pull in those …
=> Fix caching and fonts in playwright.yml

ext/js/pages/settings/recommended-permissions-controller.js, ext/js/pages/welcome-main.js, ext/welcome.html
This PR addresses #127 by adding a toggle on the welcome page, which enables the <all_urls> origin permission, and links to the permission page. 
(ESLint seems to be complaining about this, I can't for the life of me figure out why. It passes fine locally).
=> Add Intuitive Permission Toggle to Welcome Page

.github/workflows/auto-approve.yml
GitHub doesn't quite work how I want it to for a safe and consistent approval flow in this repo.
Basically, I want:
* Everything to go through the same process (all PRs, no force pushes to master), including my own code
* Nothing should go into master without my review (for devs who are pulling directly off master, it would be bad if they got infected by some malicious code)
* Extra reviews by other members are optional but encouraged
There is no way to accomplish this by default. Either (1) one can loosen branch protections, which would allow me to do force pushes, which is not as visible as a PR-based flow, and less consistent, (2) one can tighten branch protections and give more people ability to do approvals, but that would allow them to merge arbitrary code into master because of how …
=> Auto-approve safe PRs

.github/workflows/auto-approve-run.yml, .github/workflows/auto-approve.yml
Apparently, even though `pull_request_target` is supposed to run in the context of the base branch, it can't seem to access environments that are restricted to that base branch. Which seems like a bug with GitHub to me.
This is an attempt to work around that behavior, by using `workflow_run` instead of `pull_request_target`, to see if it can access branch-restricted environments.
=> Attempt to fix auto-approval CI workflow

.github/workflows/codeql.yml
The built-in GitHub CodeQL functionality seems to occasionally fail to run on some PRs (which causes OSSF Scorecard to get angry that we aren't doing static anlysis), so trying this out to see if it does any better.
=> Use custom CodeQL workflow

.github/workflows/auto-approve-run.yml, .github/workflows/auto-approve.yml
Restrict workflow permissions introduced in #218 to satisfy OSSF Scorecard
=> Restrict workflow permissions to satisfy OSSF Scorecard

ext/css/action-popup.css
Before this change, Yomitan's popup width is too small. 25px which is the [min width of an extension](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/ui/views/extensions/extension_popup.h;l=57).
After this change, Yomitan fits the content.
=> Increase yomitan popup size to fit content

README.md
Accidentally included the wrong extension ID for the dev release of yomitan, which caused the wrong version to show up in the README. This fixes the extension ID.
=> Fix README.md shields badge for chrome dev release

.github/dependabot.yml
What
====
[Grouping Dependabot version updates into one pull request](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/customizing-dependency-updates#grouping-dependabot-version-updates-into-one-pull-request)](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/customizing-dependency-updates#grouping-dependabot-version-updates-into-one-pull-request)
Why
====
Reduce unneeded PR spam, especially to the Discord channel.
=> Group minor/patch updates together in dependabot config

.github/dependabot.yml
What
====
Reduce dependabot frequency from weekly to monthly
What
====
To reduce PR spam, increase the chance of minor PRs getting grouped together, and reduce discord spam.
=> Reduce dependabot frequency from weekly to monthly

.github/workflows/publish-firefox-development.yml
What
====
`update.json` → `updates.json`
Why
====
Typo. The correct path in the metadata branch is `updates.json`
=> Fix bug in publish-firefox-development, use correct filepath

.github/workflows/create-prerelease-on-tag.yml, .github/workflows/publish-firefox-development.yml
Why
====
Currently our releases are not signed in any way, and as a result we fail the "Signed-Releases" check of the openssf scorecard.
What
====
Sign releases using the SLSA generic GitHub provenance generator.
This not only signs the release, but also generates evidence that the release was generated from the repository's GitHub workflow (as opposed to e.g., a malicious repo admin's computer who then uploaded it after).
This is even more powerful than a normal signature, because it means that it's possible for a user to entirely cryptographically verify & audit how the release artifacts were built.
=> Add SLSA provenance to releases

package-lock.json, package.json
Why
===
The web-ext dependency is:
1. massive and pulls in tons of other code (as can be seen from this +191 -6,735 lock-file diff...)
2. has a couple security vulnerabilities that have been open for months
3. is only used for linting the manifest
What
===
Remove the web-ext dev dependency, since we already lint the manifest in CI with a purpose-built action anyways
=> Remove web-ext dev dependency

package-lock.json
Now that web-ext is removed (#263), we can update this dependency.
Fixes CVE-2023-26136 (which we are not affected by, but just to be safe).
=> Update tough-cookie dependency

ext/js/background/backend.js, ext/js/comm/api.js, ext/js/comm/cross-frame-api.js, ext/js/yomichan.js
on Chrome (currently 117), the port created in the content script with runtime.connect does not properly receive an onDisconnect event when the service worker sleeps. the port created in the background with tabs.connect does receive the event, so create both ports with tabs.connect.
fixes #241.
=> Fix Chrome death, by creating both cross-frame ports in the background

ext/js/yomichan.js
when the background script starts, it sends a `Yomichan.optionsUpdated` message which is retransmitted indiscriminately.
- popups are all torn down/refreshed
- the search bar on the search page can lose state
- if a popup has been loaded on the search page, the search page can redirect/refresh
- options being edited can lose state and the options page can refresh
=> fix: page and popup state is destroyed on background wakeup

.github/workflows/create-prerelease-on-tag.yml, .github/workflows/publish-firefox-development.yml
Why
====
The SLSA generator action requires a version pin to function. Hopefully scorecard doesn't complain too much about this. It's not ideal from the security perspective, but it's the best option currently.
What
====
Switch from hash to version number.
=> Switch to version pin for SLSA generator action (as it is required)

ext/js/language/translator.js
this is based on forsakeninfinity's commit https://github.com/forsakeninfinity/yomibaba/commit/c9887d51ed5c917bb900d7964614154de1d76872
i can verify the change with JMdict, CC100, and 止める (とめる vs やめる)
=> add sort dictionary data to parse results on the search page

ext/css/structured-content.css
Related issue: [vertical-align style on structured content hyperlinks causes visual glitches](https://github.com/themoeway/yomitan/issues/271)
I'll preface this by saying I haven't actually used Yomitan. I've only tested this in the final version of Yomichan (published Oct 23 2022) and the latest version of Yomibaba. Presumably they behave identically.
I produced a [sample dictionary.zip](https://github.com/themoeway/yomitan/files/13059877/sample.dictionary.zip) with a few entries to test this style change. The relevant entry is under the word `リンク`. Images are below.
<details>
<summary>Links in Chromium with 'vertical-align' set to 'middle'</summary>
</details>
<details>
<summary>Links in Chromium with 'vertical-align' set to 'baseline'</summary>
</details>
For whatever reason, Firefox …
=> Edit `vertical-align` style for structured content hyperlinks

dev/data/manifest-variants.json, docs/permissions.md
this permission was missing when `declarativeNetRequest` was removed temporarily from Firefox.
=> restore webRequestBlocking on Firefox

.vscode/settings.json, CONTRIBUTING.md, README.md
Makes the markdown formatting much more consistent by using the [Markdown All in One](https://github.com/yzhang-gh/vscode-markdown) extension.
=> Add Markdown Formatting

ext/js/data/options-util.js
without saving, the options will be updated every time the background restarts, until any settings are modified or text scanning is toggled. for `_updateVersion21`, this means the welcome page will open repeatedly to show the same warning.
`_optionsUtil.save()` is only called in `_saveOptions`, which is only called through
- `_onApiSetAllSettings`
- `_onApiModifySettings`
- `_onCommandToggleTextScanning`
it should be safe to simply save settings after updating them.
=> save options after updating them

.vscode/settings.json
Now that we are checking in `.vscode/settings.json`, it seems preferable to have vscode auto-eslint format/fix, as eslint CI failures are quite common for people's first contribution if they don't know about it.
=> Auto-eslint in vscode

dev/data/manifest-variants.json, docs/permissions.md, ext/permissions.html
`webRequest` is used on Chrome/MV3 to surface error information from failed requests. it was added back to the declarative path by toasted-nutbread in FooSoft/yomichan#2161, but the permissions documentation did not reflect `webRequest`'s continued necessity.
=> fix: reinstate webRequest and correct the permissions docs

dev/data/manifest-variants.json, docs/permissions.md, ext/js/background/request-builder.js, ext/js/extension/environment.js, ext/permissions.html, ext/settings.html
- replace `fetchInternal` with `fetch` in the declarative path, remove `webRequest` from Chrome
- fix the flakey bug from `updateDynamicRules` on Firefox, remove the `webRequest` path entirely
- make `nativeMessaging` always optional (this has been possible for a while), unblock Firefox for Android
- fix the environment recognition for `firefox-mobile` and guard the MeCab and `nativeMessaging` settings
while enabling the `nativeMessaging` permission on Firefox for Android might break the installation, the permissions toggles don't seem to enable them anyway (permissions work a bit differently on Android).
while the extension can be signed for Android, it can't actually be installed, as the only way to install extensions on Firefox for Android requires a release on AMO.
=> Permissions fixups

.eslintrc.json, .github/workflows/playwright.yml, .vscode/settings.json, dev/data/manifest-variants.json, playwright.config.js, test/playwright/global.setup.js, test/playwright/global.teardown.js, test/playwright/integration.spec.js, test/playwright/playwright-util.js, test/playwright/visual.spec.js
Tests for search.html's clipboard monitor and adding a note to Anki. Anki responses are mocked.
* Playwright tests for search.html and Anki add note (can add more note fields to test  if wanted)
* Enable playwright experimental SW flag needed in order to intercept requests from service workers - for both the vscode playwright extension and for the GH action workflow
* Playwright manifest variant (extended off of chrome-dev) for playwright tests
* Playwright global setup/teardown to use playwright manifest variant - moves clipboardRead to required permissions
* Refactored a bit - extracted code from visual.spec.js to a new util file
notes/questions:
* The playwright manifest setup/teardown was added because I couldn't think of a way to use optional permissions - the permission popup would …
=> search.html clipboard monitor, Anki add note Playwright tests

test/playwright/integration.spec.js
Fix some flakiness with the playwright tests.
* Waits on success for inputting to the search.html page
* Waits on welcome page to close fully before moving on to actual tests - saw context.route cause an error with 'Target already closed' - seems the most likely reason
=> Playwright anki test flakiness

.eslintrc.json, .gitignore, dev/build.js, ext/data/schemas/custom-audio-list-schema.json, ext/data/schemas/dictionary-index-schema.json, ext/data/schemas/dictionary-kanji-bank-v1-schema.json, ext/data/schemas/dictionary-kanji-bank-v3-schema.json, ext/data/schemas/dictionary-kanji-meta-bank-v3-schema.json, ext/data/schemas/dictionary-tag-bank-v3-schema.json, ext/data/schemas/dictionary-term-bank-v1-schema.json, ext/data/schemas/dictionary-term-bank-v3-schema.json, ext/data/schemas/dictionary-term-meta-bank-v3-schema.json, ext/data/schemas/options-schema.json, ext/js/language/dictionary-importer.js, ext/lib/ucs2length.js, package-lock.json, package.json
Replace [JsonSchema](https://github.com/themoeway/yomitan/blob/master/ext/js/data/json-schema.js) with [ajv](https://ajv.js.org/) for dictionary validation, as it is way faster.
In particular, this drops validation time of [Jitendex](https://github.com/stephenmk/Jitendex/releases/tag/v1.5-1) **from "10 to 40 minutes" to a few seconds**.
It doesn't run into the potential eval issues with ajv, as this implementation compiles the schema in the build process and distributes them with the extension, as suggested by ajv's [own documentation](https://ajv.js.org/security.html#content-security-policy).
Some awkward edges:
* Had to work around a [bug](https://github.com/ajv-validator/ajv/issues/2209) in ajv which required vendoring in [`ucs2length` from …
=> Replace JsonSchema with ajv for dictionary validation

.github/workflows/ci.yml
Previously PRs would cause ci.yml to run twice -- now it should hopefully just run once.
=> Prevent ci.yml from running twice on PR commits

.github/workflows/create-prerelease-on-tag.yml
Seems to be broken when dependencies are involved in the build now (like ajv), so attempt to download them first. Not sure why this was even working in the first place to be honest.
=> Fix create-prerelease-on-tag.yml

.github/workflows/publish-chrome.yml
Currently it's not possible to upload to the Chrome Webstore if the extension is larger than 10MB, and with most recent changes (in particular, not minifying bundled dependencies), we are at 11MB.
I forked a couple repos in order to test a fix. If it works the fix will be upstreamed and we can switch back.
=> Switch to forked chrome webstore upload action which removes 10MB limit

README.md, ext/settings.html
In this PR, I added the `Advanced Options` header in the README, with a subheading of `Parse sentences using MeCab`. I'm not sure if this is wanted, but it is all I could come up with to reference the updated repo. In addition, I updated the link in `ext/settings.html` to the new repo.
[The repo](https://github.com/starxeras/yomitan-mecab-installer)
(I also added a period at the end of #yomitan-development, since it bugged me...)
=> Update README, Settings to include new MeCab installer repo

.github/workflows/broken-links.yml, .github/workflows/ci.yml, .github/workflows/create-prerelease-on-tag.yml, .gitignore, README.md, dev/data/legal-npm.css, ext/css/settings.css, ext/legal.html, package-lock.json, package.json
It's a bit unclear to me if it's okay to not have the full LICENSE of each dependency vendored into `legal.html`, but this method (which only includes the license name and a link) seems much nicer, easier on developers/maintainers, and more likely to stay accurate as we update dependency versions etc.
The html is generated in CI. The README markdown is still semi-manual (need to run the command and insert it into the README yourself currently).
=> Automate generation of legal information for dependencies

README.md
Update README since we are nearing our first stable release
=> Update README.md to reflect latest state of project

.github/workflows/publish-chrome.yml, .github/workflows/publish-firefox.yml, .github/workflows/release.yml
The workflow currently fails when triggered by a release, due to unset workflow_dispatch variables.
This introduces a shim `release.yml` to ensure those variables are always set.
=> Fix stable deploy on release triggers

.eslintrc.json, ext/js/core.js, ext/js/debug/timer.js, ext/js/display/display-anki.js, ext/js/display/display.js, ext/js/dom/sandbox/css-style-applier.js, ext/js/pages/settings/anki-controller.js, ext/js/pages/settings/backup-controller.js
Originally mentioned here: https://github.com/themoeway/yomitan/pull/339#discussion_r1414634810
I believe warnings are not useful information as they can (and by some people, will) deliberately be ignored, and they add a bunch of messages that are unrelated to the current working feature branch when running the test.
IMO this should be enforced as an error, and any existing locations with this problem should be explicitly annotated in the code to allow them so that they don't show up in future reports. They should really also only apply to the `ext` folder, as the dev/test stuff is command line stuff that should be expected to write to console.
=> Change no-console to error, only for ext files

.eslintrc.json, test/anki-note-builder.test.js, test/document-test.js, test/document-util.test.js, test/dom-text-scanner.test.js, vitest.config.js
This change fixes an issue where tests that were using JSDOM weren't working due to structural differences in how vitest works. Although the current setup of the tests is not exactly idiomatic for vitest, which is outside the scope of this change, they should at least work now.
=> Fix DOM tests

ext/js/background/backend.js, ext/js/language/translator.js, test/data/translator-test-inputs.json, types/ext/translation.d.ts
=> Fix Non JP Scanning Option for Kanji Dictionaries

ext/js/data/database.js
Supersedes #375, see discussion thread in that PR for more details.
Resolves #374.
=> Refactor bulk delete function

dev/manifest-util.js, ext/js/comm/frame-client.js, ext/js/core.js, ext/js/data/database.js, ext/js/data/json-schema.js, ext/js/display/display-generator.js, ext/js/dom/selector-observer.js, ext/js/general/cache-map.js, ext/js/general/task-accumulator.js, ext/js/language/translator.js, ext/js/pages/settings/keyboard-mouse-input-field.js, ext/js/pages/settings/profile-controller.js, test/json-schema.test.js, types/ext/anki-templates-internal.d.ts, types/ext/api.d.ts, types/ext/cache-map.d.ts, types/ext/core.d.ts, types/ext/dictionary-data-util.d.ts, types/ext/dictionary-database.d.ts, types/ext/dictionary-worker.d.ts, types/ext/dom-data-binder.d.ts, types/ext/dynamic-property.d.ts, types/ext/selector-observer.d.ts, types/ext/task-accumulator.d.ts
More helping prevent the usage of the `any` type.
=> Template type improvements

dev/generate-css-json.js
Some variables are ambiguously named, e.g `stylesheet1`, `stylesheet2`, `content1`, `content2`. This change renames them into more semantically meaningful names.
=> Rename ambiguously named variables

ext/js/app/frontend.js, ext/js/app/popup-factory.js, ext/js/background/backend.js, ext/js/background/offscreen.js, ext/js/comm/cross-frame-api.js, ext/js/comm/frame-ancestry-handler.js, ext/js/comm/frame-offset-forwarder.js, ext/js/core.js, ext/js/display/display-audio.js, ext/js/display/display.js, ext/js/display/search-display-controller.js, ext/js/input/hotkey-handler.js, ext/js/templates/sandbox/template-renderer-frame-api.js, ext/js/yomitan.js, types/ext/backend.d.ts, types/ext/core.d.ts, types/ext/offscreen.d.ts
This change removes the `{async}` declaration for message handlers, as this can be deduced by checking `returnValue instanceof Promise` and awaiting if `true`. It also removes the barely-used `contentScript` check on the backend, as this is probably not very useful at this point.
This can be considered a step towards improving the type safety of API; #391.
=> Simplify message handlers

ext/js/dom/document-util.js
Noticed this by testing in test-document2.html. I don't think this always used to be the case, so maybe Chromium changed or broke something.
=> Fix case where element style is undefined

ext/js/background/offscreen-main.js, ext/js/background/offscreen.js
This is more consistent with other classes. This is probably another largely undocumented style of the project, but in most situations, constructor side effects are avoided and placed into a `prepare` function. `prepare` is also a place to put `async` code which doesn't work in a constructor, but that doesn't directly apply here right now.
=> Add Offscreen.prepare for constructor side effects

ext/js/background/backend.js, ext/js/comm/api.js, types/ext/api.d.ts, types/ext/backend.d.ts, types/ext/cross-frame-api.d.ts
This change removes the unused `API._invokeWithProgress`. This used to be used to perform long-running actions such as database deletions, but these APIs were eventually moved directly into the source of the page, rather than proxying through the backend. This is possible because these actions are not performed from content scripts, but rather from privileged extension pages.
This can be considered a step towards improving the type safety and simplicity of API; #391.
=> Remove invoke with progress

ext/js/language/dictionary-importer.js, types/ext/dictionary-importer.d.ts
Reimplements _getArchiveFiles so that its only run once.
This change allows you to break early if you found the match, avoiding having to cycle through the entire fileMap for each file type.
For a dictionary with mostly files of `term_bank_?.json` format (most dictionaries), the time is improved to O(n) instead of O(n*m).
=> Minor optimizations for dictionary import

ext/js/pages/settings/profile-conditions-ui.js
This change resolves #414 . 
I believe this bug is caused by #364 . However, I am not sure if this solution captures every instance caused by this change. 
@toasted-nutbread thoughts?
=> fix add profile conditions

ext/js/background/offscreen.js, ext/js/core/api-map.js, types/ext/api-map.d.ts, types/ext/offscreen.d.ts
Further improves the setup of API map types and adds some basic descriptions. API handlers now support a generic `...extraArgs` rest parameters array if needed. The `Backend` component, for example, will need to use this.
https://github.com/themoeway/yomitan/pull/413#pullrequestreview-1793116000
#391
=> API map updates

ext/data/deinflect.json, test/deinflector.test.js
This change rebases the yomichan PR https://github.com/FooSoft/yomichan/pull/2266 for yomitan.
- できる and 出来る correctly matches 出来る as first entry
- 全うできる correctly matches to 全うする 
- 口を糊できる correctly matches to 口を糊する
=> Add 出来る/できる as inflections of する

README.md
Adds a section about recommended permissions for Firefox in README.md. 
This is a step towards more intuitive UI to grant permissions for Firefox, #127 .
Related: #330 , https://github.com/themoeway/yomitan/issues/330#issuecomment-1865891179
=> Add a Recommended Permissions FAQ section in README

ext/js/background/offscreen.js, types/ext/offscreen.d.ts
`invokeApiMapHandler` is more type-safe than `invokeMessageHandler`.
=> Update offscreen to use invokeApiMapHandler

.eslintrc.json, ext/js/yomitan.js
These were only needed because JS modules weren't used.
=> Remove unnecessary eslint global declarations

ext/js/templates/sandbox/anki-template-renderer.js, types/ext/template-renderer.d.ts
Fixes #437. Was due to the different modalities that helpers can be used in:
The following would work:
```handlebars
{{~#*inline "test"~}}
{{~#scope~}}
{{~#regexMatch "test" "gu"~}}test{{~/regexMatch~}}
{{~/scope~}}
{{~/inline~}}
{{~> (lookup . "marker") ~}}
```
The following would not work:
```handlebars
{{~#*inline "test"~}}
{{~#scope~}}
{{~set "value" (regexMatch "test" "gu" "test")}}
{{~/scope~}}
{{~/inline~}}
{{~> (lookup . "marker") ~}}
```
=> Template helper function improvements

.eslintrc.json, ext/js/background/backend.js, ext/js/core.js, ext/js/dom/dom-text-scanner.js, ext/js/language/text-scanner.js, ext/js/pages/settings/dictionary-import-controller.js, types/ext/dictionary-importer.d.ts, types/ext/dom-text-scanner.d.ts, types/ext/log.d.ts, types/ext/text-scanner.d.ts
This change narrows down the number type to an union of number literals to represent an enum. It also changes the if else matching pattern to switch statements to more closely match the enum matching patterns in other programming languages, as well as already existing code inside the project.
Part of the movement towards type safety.
=> Narrow down enum types

dev/util.js, ext/js/data/json-schema.js, ext/js/display/display-generator.js, ext/js/general/object-property-accessor.js
Follow-up of #431 .
Switch statements allow for generally easier typing and better performance characteristics. See https://github.com/themoeway/yomitan/pull/431#discussion_r1435925690.
=> switch updates

ext/js/accessibility/accessibility-controller.js, ext/js/background/backend.js, ext/js/background/script-manager.js, types/ext/script-manager.d.ts
Simplify the script manager by removing old non-MV3 stuff. This is also an effort to more succinctly fix the google docs issues.
#235; #451
=> Script manager cleanup

ext/js/app/frontend.js, ext/js/background/backend.js, ext/js/comm/api.js, ext/js/comm/frame-client.js, ext/js/comm/frame-endpoint.js, ext/js/display/search-display-controller.js, ext/js/yomitan.js, types/ext/api.d.ts, types/ext/application.d.ts, types/ext/display-search.d.ts, types/ext/extension.d.ts, types/ext/frontend.d.ts
More type safety via use of API maps, this time covering mostly all of the messages that are sent to the frontend; i.e. either content scripts or extension web pages.
=> API type safety updates

ext/js/dom/dom-text-scanner.js, types/ext/dom-text-scanner.d.ts
See https://github.com/themoeway/yomitan/pull/431#discussion_r1436233912:
My comment is a bit late on this, but these sub-functions should probably just be modifying the `seekTextNoteDetails` value that is passed into it. As it stands right now, it's repeatedly constructing and destructuring a large structure in a high-bandwidth code-path, which is probably not great. Obviously this project doesn't have performance tests currently, so I don't have hard data to back this up, but I'd imagine that this is likely less efficient.
One of the reasons why this code path was originally somewhat messy was because it was a highly-used function. That's why it was doing the weird thing where it would assign all of the member fields to local variables first, and then restore them after: for …
=> Simplify dom text scanner

ext/js/display/display-resizer.js, ext/js/language/text-scanner.js
This change suppresses some warnings:
```
display-resizer.js:48 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event.
Consider marking event handler as 'passive' to make the page more responsive.
See https://www.chromestatus.com/feature/5745543795965952
core.js:460 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event.
Consider marking event handler as 'passive' to make the page more responsive.
See https://www.chromestatus.com/feature/5745543795965952
```
=> Add explicit passive option to touchstart event

dev/data/manifest-variants.json, ext/js/accessibility/accessibility-controller.js, ext/js/accessibility/google-docs-xray.js, ext/js/background/script-manager.js, ext/settings.html, types/ext/script-manager.d.ts
=> Fix google docs

ext/js/data/options-util.js, types/ext/options-util.d.ts
More simplifications of the options util update process, since this will probably be updated more frequently.
- Same as with the message handler updates, the `async` flag is removed on the list of updates because this can be determined from the return value of update functions.
- The return value is no longer used since it was never used for anything meaningful.
- Update notes have been moved into the JSDoc comment.
=> Options util updates

test/document-util.test.js
This change fixes the document-util tests, which were not actually working as expected. Might have been a bug from #398 .
=> fix document-util tests

test/cache-map.test.js, test/core.test.js, test/hotkey-util.test.js, test/japanese-util.test.js, test/json-schema.test.js, types/test/core.d.ts
Change for loops inside test() calls todescribe.each and test.each. 
This change makes the tests more idiomatic #472 and makes the test cases more granular.
=> Test updates

ext/data/schemas/dictionary-term-bank-v3-schema.json, ext/js/display/sandbox/structured-content-generator.js, test/data/dictionaries/valid-dictionary1/term_bank_2.json, types/ext/structured-content.d.ts
This style can be used to improve the contrast and legibility of text in some circumstances.
https://github.com/stephenmk/Jitendex/issues/52#issuecomment-1890385065
=> Allow `text-shadow` style in dictionary structured content

README.md
For some device with small screens, putting badges on the same line as the project header (Yomitan) might exceed the print width. This causes it to wrap around, which is not good UI.
=> fix project header wrapping

ext/js/templates/sandbox/anki-template-renderer.js, test/anki-template-renderer.test.js, test/fixtures/anki-template-renderer-test.js
This time I _actually tested_ the code!
Fixes #531.
=> Fix AnkiTemplateRenderer again

ext/js/language/deinflector.js, ext/js/language/translator.js
Will be used in #477 so there's not some strange bitwise code all over the place.
=> Add Deinflector.rulesMatch helper function

dev/dictionary-validate.js, ext/js/dictionary/dictionary-importer.js, types/dev/dictionary-validate.d.ts, types/ext/dictionary-importer.d.ts
Solves #507 (dev dictionary validation now validates files with skipped indexes).
Also changed the `QueryDetails` in dictionary-import.js `_getArchiveFiles` to be a simple 2d array as opposed to a Map because it is more performant when looped over.
=> improve dictionary validation

ext/js/background/backend.js, types/ext/api.d.ts, types/ext/application.d.ts
Fixes an issue mentioned [here](https://github.com/themoeway/yomitan/pull/551#issuecomment-1902338251), where there was a `chrome.runtime.lastError` message being generated due to a specific message not always being handled.
This change makes it so that this message is always handled, but not always used if nothing is listening for it. Also fixes some incorrect API typing.
=> Improve handling of the applicationReady message

ext/js/pages/settings/storage-controller.js, ext/settings.html
Adds a small warning if the users is running low on storage space.
For now, the threshold for rendering the alert is set/hardcoded to `3GB`.  
It will be rendered like this:
This PR indirectly addresses #356 and #395.
=> Add warning if available storage space is low

.github/ISSUE_TEMPLATE/bug-report.md
Github now supports directly uploading JSON files into issues. This note is no longer needed and may add confusion for some users.
=> Remove note to zip or rename settings json in bug report template

ext/js/app/frontend.js, ext/js/app/popup-proxy.js, ext/js/app/popup-window.js, ext/js/app/popup.js, ext/js/background/backend.js, ext/js/background/background-main.js, ext/js/background/offscreen-proxy.js, ext/js/comm/api.js, ext/js/display/display.js, ext/js/extension/web-extension.js, ext/js/yomitan.js, types/ext/extension.d.ts, types/ext/web-extension.d.ts
This is a first step towards making a distinction between the `Yomitan` class and some of the web extension functionality it hosts. The `WebExtension` class is intended to isolate some (eventually potentially all) of the web extension APIs and store some limited state information, which currently includes whether or not the extension is unloaded. This value was previously stored on the `Yomitan` class itself, but makes more sense elsewhere.
A longer term goal I have is to better structure the overall application initialization process and to have less unneeded shared-but-not-used code across the frontend and backend. For example, search for `isBackground` in the `Yomitan` class - this code does not need to reside in this class. Another part of this effort is to reduce the number of …
=> WebExtension class

ext/data/schemas/dictionary-term-bank-v3-schema.json, ext/js/dictionary/dictionary-importer.js, ext/js/display/sandbox/structured-content-generator.js, test/data/dictionaries/valid-dictionary1/term_bank_1.json, types/ext/dictionary-data.d.ts, types/ext/structured-content.d.ts
I'd like to be able to style graphics with borders.
<table>
<tr><th width="50%">Without Border</th><th>With Border</th></tr>
<tr>
<td width="50%"><img src="https://github.com/themoeway/yomitan/assets/8003332/492b2f6c-9bdf-4ea4-a5b1-c2ce090f8166"/></td>
<td><img src="https://github.com/themoeway/yomitan/assets/8003332/a2012c57-c091-49c1-9fe6-9c18f0a8c148"/></td>
</tr>
</table>
I tested this in Chromium and exported a test card to Anki (see the image below). Seems to work okay.
<details>
<summary>Test Anki card</summary>
</details>
=> Add border styling options for structured content images

ext/data/templates/default-anki-field-templates.handlebars, ext/js/dictionary/dictionary-data-util.js, ext/js/pages/settings/anki-controller.js
There's a function hidden in the source code called pitchCategories, which returns the pitch accent categories of a word in string format. This pull request adds a new handlebar, called "pitch-accent-categories" which uses this function to return a comma delimited list of pitch accent categories for a word.
For instance, with my set of pitch accent dictionaries, running "pitch-accent-categories" on the word 「推量」returns "heiban,nakadaka", while running it on 「読め」returns "kifuku".
In order to make this work, I needed to fix a logic error in the function isNonNounVerbOrAdjective. As it was, the function would return an incorrect result if the word was both a suru verb and a noun (which is quite a lot of words!) For these words, it should return False, but it was actually returning True. To …
=> Adding a handlebar to return pitch accent categories of a word

test/deinflection-cycles.test.js, test/deinflector.test.js, types/ext/deinflector.d.ts
This change is intended to test for cycles in the deinflection definitions.
Currently this is a draft as it is incomplete, just a proof of concept.
Related: #438, #471
=> Deinflection cycle testing

ext/js/accessibility/google-docs-util.js, ext/js/app/frontend.js, ext/js/display/display.js, ext/js/display/query-parser.js, ext/js/dom/document-util.js, ext/js/dom/text-source-generator.js, ext/js/language/text-scanner.js, types/ext/display.d.ts, types/ext/document-util.d.ts, types/ext/text-scanner.d.ts, types/ext/text-source-generator.d.ts
As mentioned in #588, this is primarily removing state information from a few static utility classes. Or making them non-static.
=> Document util + google docs util state refactor

ext/js/app/frontend.js, ext/js/display/display.js, ext/js/display/query-parser.js, ext/js/language/text-scanner.js, types/ext/text-scanner.d.ts
Fixes #580.
The issue was that the `_search` function wasn't invoked when there was no text source, which resulted in the `searched` event never being invoked for that situation. This change happened during the type annotations conversion due to some confusion about how nulls should be handled.
In this change, I've done a little bit of refactoring to make this less likely to occur. The `searched` event has been split into three different events to clarify the intent:
* `searchSuccess` - happens when the search was successful and should have something displayed in the popup. This could be dictionary results, or the query parser.
* `searchEmpty` - no text source was present, or no search results were found.
* `searchError` - some error occurred.
=> Fix auto hide search popup

dev/data/manifest-variants.json, ext/js/background/offscreen-proxy.js, package-lock.json, package.json, types/dev/manifest.d.ts
Fixes one of the issues that #612 is running into. There is another typescript issue in an external library that it is also running into after this is resolved which I can see if it can be fixed, but separately.
=> Chrome types update

ext/css/display.css
There's an [annoying](https://bugs.webkit.org/show_bug.cgi?id=78957) [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1421450) in WebKit that causes the text decoration line to split when the link contains ruby text that is wider than the base ruby character. See the link to "慎重" in the image below to see what I mean. The line underneath 重 is not wide enough.
(This bug doesn't affect Firefox.)
I propose replacing the text decoration line with a bottom-border when a hyperlink contains ruby text. You might ask why we should limit it to only the links that contain ruby text. If we use a bottom border style all the time, then the external hyperlink icons (visible in the lower right corner) will also be underlined.
I also suggest adding a small amount of padding …
=> Replace `text-decoration` with `bottom-border` in links with ruby text

.github/workflows/bench.yml
CodSpeed benchmarks does not work on merge queue. 
`Error Event merge_group is not supported by CodSpeed`
=> Remove benchmark merge queue event

docs/anki-integration.md, ext/settings.html
=> Add documentation for new frequency handlebars

package-lock.json, package.json
Fixes the issue with #618 causing a typescript conflict. Pinning the version for now will make it so it won't break again.
https://github.com/vitejs/vite/issues/15714
=> Update @types/node to 20.11.5 and pin

ext/js/app/content-script-main.js, ext/js/application.js, ext/js/background/background-main.js, ext/js/comm/cross-frame-api.js, ext/js/display/popup-main.js, ext/js/display/search-main.js, ext/js/pages/action-popup-main.js, ext/js/pages/info-main.js, ext/js/pages/permissions-main.js, ext/js/pages/settings/popup-preview-frame-main.js, ext/js/pages/settings/settings-main.js, ext/js/pages/welcome-main.js
Further trying to standardize the application initialization process and the Application class. This change makes it so `Application` is no longer used on the Backend, and there is a common method of initializing all frontend pages. The goal of this is to make it so that the objects have to do less inside of their own prepare function, and it's instead moved outside of it. To this end, the tabId and frameId are now computed up before constructing some of the classes that need it. This can still be further improved, as I think there are other places that still redundantly request the frame ID, but that is a separate issue.
Note: this PR will be easier to review if whitespace diffs are disabled.
=> Update application init process

ext/js/input/hotkey-help-controller.js
Fixes a bug which occurred due to an implicit `any` type.
=> Fix hotkey helper not properly returning attributesArray

.github/dependabot.yml, package-lock.json, package.json
_Hopefully_ this fixes dependabot's nagging once and for all.
I don't remember exactly why I pinned typescript in 19f359af78c052c7d3083fc353d37c606444f179, but I think it's no longer a problem.
=> Dependency version pinning

.github/workflows/publish-chrome-development.yml, .github/workflows/publish-chrome.yml
https://github.com/cardinalby/webext-buildtools-chrome-webstore-upload-action/issues/10
=> `publish-chrome*`: update upload action to avoid error with `author`

ext/data/templates/anki-field-templates-upgrade-v24.handlebars, ext/js/data/options-util.js, package.json, test/data/json.json, test/data/vitest.options.config.json, test/options-util.test.js, types/ext/options-util.d.ts
Adds `test-options-update` test. And changes to actually test the latest handlebars update changes. The test definitions here are quite static but having these tests be updated before merging updateVersion things would be a good idea. Hopefully to prevent #670 from happening again.
I had to add `if (profileOptions.dictionaries.length > 0) {` to the dict updates here due to the tests trying to run through some (maybe old?) dict that isn't in an array. Not sure if that's the best way to do that. 
Not the most knowledgeable on tests so not sure if I've done everything else right either.
=> Add and fix tests with options upgrades

ext/data/schemas/options-schema.json, ext/display-templates.html, ext/js/background/backend.js, ext/js/comm/anki-connect.js, ext/js/comm/api.js, ext/js/data/options-util.js, ext/js/display/display-anki.js, ext/js/pages/settings/anki-controller.js, ext/js/pages/settings/keyboard-shortcuts-controller.js, ext/settings.html, test/options-util.test.js, types/ext/api.d.ts
This PR is to demonstrate a feature I had in mind in #610.
Now, when clicking the book icon in the pop-up, all duplicate Anki notes are shown (using 一括 as an example):
The "view note(s)" button defaults to showing all notes[^1] in the browser, as opposed to only showing one card as it's done today.
Instead, the default behavior could be left unchanged, and we could add an option to "View all notes" inside the right-click context menu.
Find a term with several duplicate notes in Anki
**Book icon**
**Context menu**
**"View Notes" Hotkey (Alt + V)**
**Regression**
[^1]: This works fine even if there is only one note in the list.
=> Show all duplicate notes on click

ext/js/app/content-script-main.js, ext/js/app/frontend.js, ext/js/app/popup-factory.js, ext/js/application.js, ext/js/background/backend.js, ext/js/comm/cross-frame-api.js, ext/js/comm/frame-ancestry-handler.js, ext/js/comm/frame-offset-forwarder.js, ext/js/display/display.js, ext/js/display/popup-main.js, ext/js/display/search-display-controller.js, ext/js/display/search-main.js, ext/js/pages/settings/popup-preview-frame-main.js, ext/js/pages/settings/popup-preview-frame.js, types/ext/application.d.ts, types/ext/extension.d.ts, types/ext/frontend.d.ts
This change removes a lot of the redundancy involving tabId/frameId on non-background scripts. Application already computes this during initialization, so there is no reason to recompute it. The only tricky bit here is primarily that there are bunch of places that `null` needs to be checked, and the `undefined` value was changed to `null` on the `ContentOrigin` type.
=> Application data refactor

ext/css/search.css, ext/js/display/search-display-controller.js, ext/search.html
(The HTML is just moved around a little so it doesn't jump when the kana option dissapears)
=> disable kana conversion on search page for other languages

ext/action-popup.html, ext/background.html, ext/info.html, ext/issues.html, ext/js/app/content-script-main.js, ext/js/application.js, ext/js/display/popup-main.js, ext/js/display/search-main.js, ext/js/pages/action-popup-main.js, ext/js/pages/info-main.js, ext/js/pages/permissions-main.js, ext/js/pages/settings/popup-preview-frame-main.js, ext/js/pages/settings/settings-main.js, ext/js/pages/welcome-main.js, ext/legal.html, ext/offscreen.html, ext/permissions.html, ext/popup-preview.html, ext/popup.html, ext/search.html, ext/settings.html, ext/template-renderer.html, ext/welcome.html
Since there's only one script now, it makes more sense to have it start loading in the `<head>` tag rather than at the end of the `<body>`. This may only really make a potentially-noticeable speed difference on the settings page since it's a _massive_ document.
For context about this change and #706, I'm trying to look into some cleanup of the settings pages code and see if I can make it cleaner to design content for it, and these were the first cleanup steps in the process.
=> Application main updates

ext/js/dom/html-template-collection.js, ext/js/pages/settings/anki-controller.js, ext/js/pages/settings/settings-controller.js
Fixes #721. I searched for other places in the code that might have this issue, didn't see anything else.
=> Fix anki template field marker menu

test/playwright/integration.spec.js, test/playwright/playwright-util.js
This change improves the type safety of the playwright test code. Previously, there were some standard objects being treated as `Map`s, and a few other type assumptions based on the use of the implicit `any` type.
=> Improve type safety for playwright stuff

.eslintrc.json, ext/js/app/frontend.js, ext/js/background/backend.js, ext/js/comm/api.js, ext/js/comm/clipboard-monitor.js, ext/js/display/display-generator.js, ext/js/display/display.js, ext/js/display/query-parser.js, ext/js/display/sandbox/structured-content-generator.js, ext/js/display/search-display-controller.js, ext/js/language/language-descriptors.js, ext/js/language/languages.js, ext/js/language/text-scanner.js, ext/js/language/text-utilities.js, types/ext/api.d.ts, types/ext/application.d.ts, types/ext/display.d.ts, types/ext/language-descriptors.d.ts
Resolves #717.
This change generalizes how languages are checked to see if a string "may be translatable". This now supports additional languages, although it is only explicitly set up for Japanese at this point.
There are two functions worth noting:
* `getLanguageFromText` is used to determine which language a string "might" be using. This is only used for assigning a `lang` attribute on the generated content.
* `textMayBeTranslatable` is used to determine if the text might be translatable into that language. This is used to filter out things for the clipboard monitor as well as a lesser-used edge case of determining whether or not image alt text, button text, etc. should show the query parser in the standard search popup.
=> "isJapanese" check move

dev/dictionary-archive-util.js, dev/dictionary-validate.js, dev/lib/zip.js, dev/util.js, test/database.test.js, test/dictionary-data-validate.test.js, test/fixtures/translator-test.js, test/playwright/integration.spec.js
=> Update to zip.js for tests

ext/js/templates/sandbox/anki-template-renderer.js
Fixes #718
Fixes #682
Fixes #686
Due to the new handlebars changes that introduce escaping there, we've ended up with double escaping.
For example `'` -> `&#x27;` -> `&amp;#x27;` and this only gets parsed back one step not two so the output is `&#x27;`. Only the `&` ends up getting unescaped.
I've removed this extra escaping step from the template renderer.
=> Remove redundant escaping

.eslintrc.json, ext/js/background/backend.js, ext/js/background/offscreen-proxy.js, ext/js/comm/frame-client.js, ext/js/core/object-utilities.js, ext/js/core/utilities.js, ext/js/data/anki-util.js, ext/js/data/options-util.js, ext/js/display/display-generator.js, ext/js/display/display-history.js, ext/js/input/hotkey-help-controller.js, ext/js/pages/settings/backup-controller.js, ext/js/pages/settings/extension-keyboard-shortcuts-controller.js, ext/js/pages/settings/persistent-storage-controller.js, ext/js/pages/settings/settings-controller.js
There are a lot of places in the code that have casts that really shouldn't be necessary. This happens in a lot of places due to using `typeof x === 'object' && x !== null`, this unfortunately doesn't provide TypeScript with enough information to be allowed to do `x.someProperty` and yield an `unknown` type. This is kind of why the `core.SerializableObject` and `core.UnknownObject` types exist.  These should eventually be replaced with `Record<string, unknown>` for simplicity and improved standardization.
This PR is a first step towards this by making the `isObject` (now `isObjectNotArray`) function return improved type info, which should reduce the amount of checks/casts necessary when these functions are used. This can be addressed going forward after this, right now this just updates …
=> Object utilities

ext/js/templates/sandbox/anki-template-renderer.js
Missed this in #722
_safeString only needs to be added to plaintext dictionary entries due to structured content and image already having it applied by _getHtml.
=> Mark string and text glossary content as safe to avoid broken <br>

ext/data/templates/anki-field-templates-upgrade-v27.handlebars, ext/data/templates/default-anki-field-templates.handlebars, ext/js/data/options-util.js, test/options-util.test.js
The output of sentence-furigana needs to not be escaped. With the new handlebars changes this requires using `{{{ }}}` syntax. https://handlebarsjs.com/guide/expressions.html#html-escaping
As far as I can tell this is the only handlebar with this issue but I haven't thoroughly tested every single one.
I also had to make a small change to the version 25 update or `npm run "test:unit:options"` test would fail due to one out of three profiles having `profile.options.input` set to undefined. (does anyone run this test when making changes?)
=> Fix sentence-furigana template

.github/workflows/ci.yml, package.json, test/data/vitest.options.config.json, test/data/vitest.write.config.json, test/dictionary-data.write.js
Resolves #https://github.com/themoeway/yomitan/pull/733#issuecomment-1974770356.
Fixes an issue with the test data writing where it was missing an extra newline.
The standalone vitest config files were updated because it seems that the previous wildcard was being used relative to the root directory. So running `npm run test:unit:options` could actually end up invoking stuff outside of the project directory:
```
✓ ../yomitan-new/test/options-util.test.js (3)
✓ ../yomitan-old/test/options-util.test.js (3)
✓ ../yomichan/test/options-util.test.js (3)
✓ test/options-util.test.js (20)
```
=> Ci updates

ext/css/search.css
Fixes #753
This appears to have been changed in #705 to align the search options and search textbox but did not take into account the selection arrow. I've fixed the padding on the arrow while keeping the search options and search textbox aligned.
=> Fix entry selection arrow padding in search

ext/data/templates/anki-field-templates-upgrade-v27.handlebars, ext/data/templates/default-anki-field-templates.handlebars, ext/js/data/options-util.js, ext/js/templates/sandbox/template-renderer.js, test/options-util.test.js
Fixes #744 
Basically, it seems the handlebars `~` removes whitespace but not newlines. Instead of trimming the string outputted by handlebars this just removes the newlines.
=> preserve whitespace in cloze-prefix and cloze-suffix

dev/bin/build.js
After reading the CONTRIBUTING.md, it seemed to me that the supposed support for the positional target CLI args for build.js is missing, so I went ahead and added it in.
If I'm mistakenly implementing an existing feature, please let me know!
=> Support build.js target positional arguments

ext/js/display/display-anki.js
Looking at #818 and the code, I think the buttons are missing entirely, rather then grayed out, only when there is an anki error. The `ankiError` here seems to not get logged anywhere, so at least logging it to see what error it is might help.
=> log anki error when hiding button

ext/js/background/backend.js
Fixes #817
cannotAdd is no longer a possible differentiator for if a card is a dupe and cannot be used to check whether notesInfo needs to be pulled.
=> Fix tags not displaying for duplicate cards

ext/js/background/backend.js, ext/js/comm/anki-connect.js, test/playwright/playwright-util.js
Fixes #818.
Reverting to using canAddNotes to avoid issues for users with older AnkiConnect version not supporting `canAddNotesWithErrorDetail` (introduced in [24.1.21.0](https://git.foosoft.net/alex/anki-connect/commit/bbf271c5ac611705accbf4ec9dbaa3382ba439ec)).
To simulate the original issue:
=> Fix #818: Revert to using canAddNotes

ext/js/background/backend.js, ext/js/data/anki-util.js, ext/js/display/display-anki.js
Fixes #788
It isn't possible to get the noteId for a duplicate note of a different note type without specifically searching exact sort field of every note type. A filler noteId that cannot exist in anki (`-1`) can be used to allow the dupe's identity to not be lost.
=> Fix duplicate check not working across note types

ext/css/search.css
Supercedes #781
Fixes a regression added in #754
Previously, the search bar and header were lined up with the arrow on dictionary listings to indicate the selected listing. This looks horrible on small screens due to the search bar being exactly on the edge of the screen on the left side.
Now, the search bar and header line up with the dictionary listings themselves instead of having a negative offset.
=> Fix search header left margins on small screens

.github/workflows/publish-firefox-development.yml
cardinalby/webext-buildtools-firefox-sign-xpi-action v1.0.7 is problematic see https://github.com/themoeway/yomitan/actions/runs/8765698303
Partial revert of #798
=> Revert cardinalby/webext-buildtools-firefox-sign-xpi-action

.github/workflows/publish-firefox-development.yml
Issue caused by 1.0.7 should be fixed now https://github.com/cardinalby/webext-buildtools-firefox-sign-xpi-action/issues/9#issuecomment-2067721858
=> Bump webext-buildtools-firefox-sign-xpi-action to 1.0.8

ext/js/display/search-display-controller.js
The profile select input hasn't been updating when the profile is changed elsewhere, or with the keyboard shortcut, or when profiles are added/deleted/renamed.
=> fix profile select on search page not updating

ext/data/templates/anki-field-templates-upgrade-v33.handlebars, ext/data/templates/default-anki-field-templates.handlebars, ext/js/data/options-util.js, test/options-util.test.js
Turns out there were some other handlebars that needed fixing besides `{sentence-furigana}` #733
The output of definition.cloze needs to not be escaped. This requires using `{{{ }}}` syntax. https://handlebarsjs.com/guide/expressions.html#html-escaping
Text-based `getMedia` also should not be escaped (`{clipboard-text}` and `{selection-text}`).
Fixes #856
=> Fix definition.cloze and text-based getMedia in handlebars being escaped

ext/css/display.css
In #862 I added css to remove the furigana on the query parser term when `Term display style` was set to Plain term. This created a conflict with the `Reading mode` setting which is what is supposed to control the query-parser-term styling instead.
This PR reverts `Term display style` to only controlling the headword-term and headword-reading. This does not revert any previously added functionality but currently the settings to get the behavior where the query-parser-term furigana is hidden are positioned horribly, #884 will fix that.
=> Fix Term display style and Reading mode css conflict

ext/action-popup.html, ext/css/action-popup.css, ext/js/pages/action-popup-main.js
Tested on Firefox android, Kiwi browser, and Chromium desktop (to verify it only displays on mobile).
This does not affect the look of the desktop popup even though some values have been changed there it matches exactly.
Before             |  After
:-------------------------:|:-------------------------:
=> Fix mobile action-popup

.eslintrc.json, dev/dictionary-validate.js, ext/js/accessibility/google-docs-xray.js, ext/js/background/backend.js, ext/js/background/offscreen-proxy.js, ext/js/background/script-manager.js, ext/js/comm/anki-connect.js, ext/js/comm/frame-ancestry-handler.js, ext/js/comm/frame-client.js, ext/js/data/anki-note-builder.js, ext/js/data/database.js, ext/js/data/json-schema.js, ext/js/data/options-util.js, ext/js/dictionary/dictionary-data-util.js, ext/js/display/display-history.js, ext/js/input/hotkey-help-controller.js, ext/js/language/translator.js, ext/js/pages/settings/backup-controller.js, ext/js/pages/settings/dictionary-import-controller.js, ext/js/templates/anki-template-renderer.js, ext/js/templates/template-renderer-media-provider.js, ext/js/templates/template-renderer.js, test/dom-text-scanner.test.js, test/fixtures/dom-test.js, test/handlebars.test.js, types/ext/translation-internal.d.ts
Port of #764 considering nutbread is insactive
=> Update eslint unsafe rule

dev/data/structured-content-overrides.css, ext/css/structured-content.css
I edited the CSS a bit so that it looks more pleasing. Before, if there were many details next to each other the grey lines would overlap and it looked quite bad. Here are example pictures:
=> Change Details and Summary Tags CSS

.github/workflows/playwright_comment.yml
Closes #900. As far as I can tell, this edit to the GitHub Actions pipeline should be sufficient, and the change works on my fork :)
=> Remove playwright's success PR comments

ext/js/display/search-display-controller.js
#840 added support for refocusing on backspace but left out support for `ctrl + backspace`
=> Allow ctrl + backspace to refocus the search

docs/anki-integration.md, ext/css/settings.css, ext/js/comm/anki-connect.js, ext/js/pages/settings/anki-controller.js, ext/js/pages/settings/anki-deck-generator-controller.js, ext/js/pages/settings/settings-main.js, ext/settings.html
Currently supports exporting a list of words either directly to Anki or to Anki's `Notes in plain text` file format.
Tested on Firefox and Chromium.
Demo:
https://github.com/themoeway/yomitan/assets/61125188/b7445557-a2cc-4f25-81ac-13f720e77b95
=> Add option to bulk generate anki cards

ext/js/background/backend.js, ext/js/pages/action-popup-main.js
Fixes #515
It isn't obvious from the code changes but this is what is going on here:
Old behavior:
```
shift click search button -> popup search opens -> popup search closes -> new tab opens with search page
```
This all happens instantly so the popup search is never seen.
New behavior:
```
shift click search button -> popup search opens -> search page opener sees 'popup' mode and does not open the search page
```
=> Restore shift click behavior for search button opening as a popup

ext/js/pages/settings/dictionary-import-controller.js
Fixes #723
I think this issue is due to calling `triggerDatabaseUpdated` without an await before `_addDictionarySettings` causing a race condition. But due to the nature of this bug there's no way to be 100% sure.
Simply awaiting `triggerDatabaseUpdated` doesn't work due to it calling `ensureDictionarySettings` conflicting with `_addDictionarySettings` and creating duplicate dict settings. (`ensureDictionarySettings` makes sure all dicts have settings entries and adds one if it is lacking. `_addDictionarySettings` adds a setting regardless of whether one exists already.) 
Running `triggerDatabaseUpdated` after `_addDictionarySettings` appears to work perfectly fine.
I've also allowed `getOptionsFull` to retry up to 10 times if it fails, catching any errors so the dict import process is …
=> Catch and handle errors if getOptionsFull fails

ext/js/input/hotkey-handler.js
Currently, shortcuts can be set in the settings using modifiers only without any other key but these shortcuts don't function.
This fixes that by allowing the key to be null when registering hotkeys.
=> Allow keyboard shortcut hotkeys to be modifiers only

ext/js/language/text-scanner.js
Fixes #533 
Something worth noting here is how the following interations work:
Interaction 1:
```
move mouse -> stop mouse -> scan -> close popup -> move mouse -> stop mouse -> scan
```
This works totally fine. Both times the user presses the button to scan they will get the popup and the word will be scanned.
Interaction 2:
```
move mouse -> stop mouse -> scan -> move mouse (first popup is not closed) -> stop mouse -> scan
```
This does not work. The user will get the first popup but then the second popup won't show (unless the user was scanning a word inside the first popup). This is because the user's browser will have focused inside the popup window and all event listeners outside of it can no longer access the keypresses.
On a normal webpage this wouldn't be an issue but Yomitan …
=> Cache mousemove and hook keyboard to allow scanning at mouse position while mouse is no longer moving

ext/js/pages/settings/anki-controller.js, ext/settings.html
Nice UX thing. If it fails (anki not open or something), it just does nothing.
=> Update anki settings when Configure Anki card format button is clicked instead of requiring page refresh

ext/js/app/frontend.js, ext/js/dom/text-source-range.js, ext/js/pages/settings/keyboard-shortcuts-controller.js, ext/templates-settings.html
Currently, the `Scan selected text` keyboard shortcut ignores the selection if it finds a word bigger than the selection. It makes more sense that `Scan selected text` would only scan the selected text and not expand outside of it.
To not break existing use cases of the previous `Scan selected text` I've added `Scan text at selection` which has the previous behavior and is more in line with what would be expected of that name.
Fixes #792
=> Make Scan selected text lazy and add Scan text at selection

ext/settings.html
These got mistakenly removed in the settings rework and causes an error to throw upon trying to import or export a dictionary collection.
Ideally these settings items would be hidden while not importing or erroring since they make things look a bit ugly but for now the previous behavior can just be restored.
=> Fix collection import error and progress display

ext/js/language/text-scanner.js
Should help prevent unintended scanning while a user is typing and hits the shift key and the scan key is the shift key.
=> Disallow scanning while mouse is not moving if input, textarea, or editable elements are active

ext/js/input/hotkey-handler.js
In #916 I fixed support for shortcuts that were modifiers only. However, I mistakenly null checked the modifiers array instead of length checking it.
This allows for setting and registering a shortcut that has no key trigger conditions. I'm not exactly sure what is going on with shortcuts like this but they do wacky things and trigger "randomly" when they shouldn't.
=> Disallow hotkeys with no keys or modifiers

ext/images/add-duplicate-term-kana-blue.svg, ext/images/add-duplicate-term-kana.svg, ext/images/add-duplicate-term-kanji-blue.svg, ext/images/add-duplicate-term-kanji.svg, ext/images/add-term-kana.svg, ext/images/add-term-kanji.svg
This is to make the svg xml code readable/editable manually. Consistent colors are now used across the buttons, which causes some imperceptible visual changes.
=> refactor svg code for icons

ext/css/action-popup.css
#extension-info is the thing that says "Yomitan v24.5.14.0" or whatever version in the mobile popup (theres some screenshots of this on #886). If the version number is too long (for example v99.99.99.99) this can horizontally extend the action popup page beyond the device's view.
Dev builds of Yomitan also suffer badly from this with the addition of the incredibly long "(development build)" text.
This fix puts "Yomitan" and the version number on different lines if it gets too long.
=> Add word wrap to #extension-info on mobile to prevent page horizontal elongation

ext/js/language/language-descriptors.js, types/ext/language-descriptors.d.ts
Also wondering if it might make sense to separate mandarin into `zh-Hant`, `zh-Hans` since those have a distinction for font rendering.
=> Add Cantonese

ext/js/pages/settings/anki-controller.js
#934 had some edge cases where things wouldn't get properly updated due to old settings still being present. This reverts #934 and instead reloads all of the Anki settings when clicking on `Configure Anki card format...`.
=> Update anki settings on Configure Anki card format click

ext/js/display/search-display-controller.js
Due to a 23 year old Firefox bug (https://bugzilla.mozilla.org/show_bug.cgi?id=85686) window.getSelection() does not behave the same on Firefox as it does on Chromium.
It is not possible to get the current selection using this if a textarea or input is where the selection is located on Firefox. It is possible to achieve this using other methods but none of these methods work for fetching the selection anywhere on the page. So there is no equivalent of window.getSelection() to be used.
To avoid jank I've rewritten the code to check whether the user has the browser page focused instead using document.hasFocus(). If the user has the browser page focused, updating the search from a clipboard copy is blocked.
I searched the blame for this code back to when it was added to check if there were …
=> Browser agnostic search page clipboard and selection handling

ext/css/material.css, ext/css/settings.css, ext/images/down-chevron.svg, ext/images/up-chevron.svg, ext/js/pages/settings/dictionary-controller.js, ext/settings.html, ext/templates-settings.html
Depends on #981. It doesn't make sense to have this ui unless the dict order sorting works properly.
Repositioning dictionaries is a huge pain right now and requires two button clicks to move a dictionary a single space up. Using `Move to...` or having to repeatedly hit the menu button and then move up or down is not a good user experience.
Ideally we want something like drag and drop but I think this change helps a bit before we get to that.
Screenshot:
Tested on Firefox, Chromium, Firefox Android, and Kiwi browser.
=> Move dictionary up and down buttons out of kebab menu

ext/css/settings.css, ext/js/pages/settings/dictionary-import-controller.js, ext/js/pages/welcome-main.js, ext/settings.html
Adds drag and drop functionality and the option to import dictionaries from a url.
=> Rework dictionary import UX

ext/js/pages/settings/sort-frequency-dictionary-controller.js
These aren't supposed to be able to be null/undefined but a user reported hitting an issue where it was undefined and caused an error when trying to access `counts.termMeta`. Possibly something with a malformed dictionary. But regardless we should handle this case.
=> Add check for counts and counts.termMeta

ext/js/dom/document-util.js, ext/js/language/text-scanner.js
More Firefox bugs/inconsistencies yay!
For KeyboardEvent, when modifiers are pressed on Firefox without any other keys and the focus is in a textarea or input, the keydown event does not contain the last pressed modifier as event.{modifier}. This also occurs when modifiers are sent through virtual keycodes (often the result of software keyboard remapping).
Chrome and Firefox (outside of a textarea or input) do report the modifier in both the event.{modifier} and the event.code so we must check if the modifier has already been added to not duplicate it.
The textarea and input part of this usually doesn't matter (we already don't allow scanning without mousemove in an input or textarea) but it makes it very annoying to set up modifier only keybinds for shortcuts. You had to press more keys …
=> Fix detection of modifiers on Firefox in textarea or input and modifiers sent through virtual keycodes

ext/js/app/frontend.js, ext/js/language/text-scanner.js
This can occur if the scan button is pressed multiple times without moving the mouse after the popup appears and the popup contains a saved mouse position from a previous popup that matches the position of scannable text in the current popup.
This change clears the mouse position when the popup is closed so there will never be any saved mouse position when the popup is opened.
Minimal reproduction steps for this issue:
1. Scan a word
2. Mouse over scannable text within the popup
3. Close the popup without moving the mouse (press esc) while the cursor is still above the scannable text in the popup
4. Mouse over word scanned in step 1 and do not move the mouse after this
5. Press the scan button to scan the word
6. Press the scan button again
You will now have a second popup even though the …
=> Fix chance of multiple popups appearing when scan key is pressed multiple times without moving

ext/js/background/backend.js, ext/js/display/search-display-controller.js
Allows the search page clipboard monitor to run in popups and disallows the global clipboard monitor from messing with popups after initialization.
This allows the search page to have control over the clipboard so things will work the same on both the search page popup and the normal search page when we're updating code there.
Fixes #786.
Also fixes a bug where text copied on the search page popup updates the search.
=> Fix clipboard monitor in popups

ext/js/comm/api.js
This error is sometimes user facing and it could be confusing to users as to what to do about it. Almost always this is fixed by refreshing the page.
=> Add note about refreshing page in api invoke error

ext/js/dom/dom-text-scanner.js
rb tags should be ignored by layout aware scanning. This bug only appears on firefox presumably due to chromium not properly supporting rb tags.
Fixes #888
=> Disallow breaking on rb tags when layout aware scanning is enabled

ext/data/schemas/dictionary-index-schema.json
While `sh` is a deprecated ISO code, it's still in use by e.g. Wiktionary, so it should be allowed.
=> allow dictionary language to be Serbo-Croatian

README.md
Resolves #1014 as Kanjium is no longer included in this project.
The EDRDG license is not needed since the JMdict stuff was moved to https://github.com/themoeway/jmdict-yomitan
=> Remove Licenses

.eslintrc.json, ext/js/language/language-descriptors.js, ext/js/language/sh/serbo-croatian-text-preprocessors.js, types/ext/language-descriptors.d.ts
This differs from the existing latin diacritics prepocessors in that čćžš and maybe some others need to be kept, but vowel accent marks need to be removed.
=> [sh] preprocess accent marks

ext/js/language/text-scanner.js
Fixes #1011 
Japanese was working because of [this line](https://github.com/themoeway/yomitan/blob/b6341f312d8332ccff0d928d936e9290da0e9584/ext/js/language/ja/japanese.js#L340). Other languages haven't implemented `isTextLookupWorthy` so it pops up for other languages
Tested on youtube by holding the modifier key and hovering over buttons -> no popup
Tested normal functionality by scanning to false positives.
=> Add text length check to isTextLookupWorthy

benches/canary.bench.js
Add a canary benchmark to detect if there is noisy in our testing environment. This should not change or fluctuate too much or it would indicate flakiness.
Closes #892
=> Add canary benchmark

ext/js/language/language-descriptors.js
This PR updates the spanish dictionary sample word from "acabar de" to "leer".
- Updated language-descriptors.js line 83
- Fixes #1052
Reports of "leer" being a better more standardized example
=> [es] Change example word to 'leer'

ext/js/dom/text-source-range.js
Fixes: #1030 
In the context in which `this._disallowExpandSelection` is `true` (for example when we use the context menu scan or the shortcut), we don't concatenate the existing `TextSourceRange` content with what the `DOMTextScanner` scans, but in either case we return the number of characters scanned as if we expanded the selection, resulting in `TextSourceRange` being internally consistent and having a `this._content.length` being smaller than what `setEndOffset` returns, causing indexing into the `TextSourceRange` string to be undefined.
=> Don't move offset when disallowExpandSelection is true

.vscode/launch.json, ext/js/dom/dom-text-scanner.js, test/data/html/text-source-range.html, test/data/json.json, test/dom-text-scanner.test.js, test/text-source-range.test.js
Our DOMTextScanner will enter the first `ELEMENT_NODE` upon a backwards seek, even if we're initializing our DOMTextScanner with an offset of `0`. This can cause duplicate content to be produced.
Example in the `text-source-range.test.js`:
```html
<test-case id="text-source-range">
<p>山</p>
</test-case>
```
I'm starting from `text-source-range.js` to create a `TextSourceRange` object from a constructed range. I'm creating a `Range` object that has `<test-case id="text-source-range">` as its `startContainer` and `</test-case>` as its `endContainer`.
The range object has a `startOffset` of `0` and `endOffset` of `3`. The `3` represents that the end range is set at `<test-case id="text-source-range">` + 3 nodes. In this case this would be:
Node 1: `#text` of value `\n`
Node 2: `<p>`
Node 3: …
=> Fix DOMTextScanner entering initial div on backwards seeks

ext/js/app/theme-controller.js
`auto` was renamed to `site` internally in update18. This switch arm was matching the wrong value.
=> Fix auto popup theme shadow not applying

ext/css/popup-preview.css, ext/data/schemas/options-schema.json, ext/js/app/frontend.js, ext/js/app/theme-controller.js, ext/js/display/display.js, ext/js/display/query-parser.js, ext/js/language/text-scanner.js, ext/js/pages/action-popup-main.js, ext/js/pages/info-main.js, ext/js/pages/quick-start-guide-main.js, ext/js/pages/settings/popup-preview-frame.js, ext/js/pages/settings/settings-display-controller.js, ext/settings.html, ext/welcome.html, types/ext/display.d.ts, types/ext/query-parser.d.ts, types/ext/text-scanner.d.ts
What the auto option does:
- Welcome, settings, permissions, quick start, search, and info pages all use the browser's default theme
- The popup adapts theme based on the theme of the webpage it is being rendered on
I've also set this to be the default. It makes the popups much nicer to read since they don't clash with the page they're being rendered on. This should be a nicer experience for new users.
The reason this pr touches frontend, query-parser, and text-scanner is because information from the parent page is required and due to the popup being a separate webpage this cannot easily be accessed. It is being sent through the same way as other information such as the parent page url and sentence (for later use in anki handlebars).
=> Add auto option to body theme

ext/css/settings.css
These get squeezed in a bit because it looks worse to have them spread apart and on pc theres no issue but on touchscreens it could be a bit rough.
On mobile:
| Before      | After      |
| ![image](https://github.com/themoeway/yomitan/assets/61125188/137ffe9c-99d2-43bf-a9f2-9278528ff9bd) | ![image](https://github.com/themoeway/yomitan/assets/61125188/3211aa63-fab6-4636-97c6-282bb87dc056) |
=> Set up down buttons to default button size when on mobile

ext/css/settings.css
These got missed in the theming updates. Affects scrollbars in modals such as the dictionary listing when a user has enough dicts to make it scroll.
=> Add modal-body to scrollbar styling

ext/js/app/popup.js, ext/js/display/display.js, ext/js/pages/settings/popup-preview-controller.js
Another special case for popup preview. Fixes popup preview display when selecting auto for shadow and light or dark for body. This does not affect normal webpages and scanning.
Also split out the popup preview url checking since it's being used in two places now. Theres also no longer the chance of any issue if a user is viewing a website with a page named `popup-preview.html`.
This list `http, https, ws, wss, ftp, data, file` comes from here https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns#scheme. Extensions are not allowed to operate on any other protocols (except `(chrome-)extension` but we don't want to check for that here).
Chromium locks this down even further to just `http, https, file` …
=> Fix shadow in popup preview when auto is selected

.gitignore, dev/data/legal-npm.css, ext/legal-npm.html
We link to this in legal.html. It should not be ignored.
The theming of this is a bit unfortunate. With the library we use to generate this file, it is not possible to embed js to fetch our theme and it's in an iframe so the parent page cant touch it. I've made it always use the browser/system theme instead.
=> Fix missing legal-npm.html

ext/css/action-popup.css
On pc the loading is so small this doesnt really matter but on mobile the action popup is full page. This removes the flashbang upon opening action popup on mobile when dark theme is selected in browser settings.
=> Use browser theme for loading on action popup

ext/css/settings.css
When opening a page, browsers default to thinking the page is in light mode. No background = white background.
This creates flashbangs when opening yomitan pages due the pages being hidden and thus having no background before they are loaded. Due to our themes being applied after the browser's page load (js modules can't be blocking) these pages don't fall back on the browser's background which does do light and dark properly.
But we can set the background explicitly for the browser to use during the downtime between the page being loaded in the browser and it being loaded in Yomitan.
=> Remove flashbangs on page transition

ext/css/search.css
Missed this in #1101. Search page doesnt use settings.css like all the other pages.
=> Remove search page flashbang on page transition

ext/action-popup.html, ext/css/action-popup.css, ext/js/pages/action-popup-main.js
Fixes #1104
|       |       |
| ![image](https://github.com/themoeway/yomitan/assets/61125188/b1612d20-6c3d-4ff0-b8fe-0951df4f21ef) | ![image](https://github.com/themoeway/yomitan/assets/61125188/53474e1f-3478-4e2e-b650-1ce6f9adf072) |
=> Add profile selector to mobile action-popup

.eslintrc.json, ext/js/language/language-descriptors.js, ext/js/language/vi/viet-text-preprocessors.js, test/language/viet-text-preprocessors.test.js, types/ext/language-descriptors.d.ts
This PR adds diacritics normalization for Vietnamese and places the diacritics according to the old style or new style.
References:
https://en.wikipedia.org/wiki/Vietnamese_alphabet#Tone_marks
https://github.com/enricobarzetti/viet_text_tools/blob/master/viet_text_tools/__init__.py
=> Add diacritics normalization preprocessors for Vietnamese

ext/css/search.css, ext/js/display/search-display-controller.js
Only occurs on firefox, something with the button size is calculated differently from chromium. We can fix it by setting an explicit height for the button. Included in SearchDisplayController to allow the button to grow at the same scale as the search box when newlines are added.
| Before      | After      |
| ![before](https://github.com/themoeway/yomitan/assets/61125188/afe7eeb0-f386-449d-9755-da4311a70e41) | ![after](https://github.com/themoeway/yomitan/assets/61125188/aa09f882-bdea-4c57-9e77-e4ef55335890) |
=> Fix firefox search button 1px off of search textbox

ext/css/settings.css, ext/settings.html
This modal isnt big enough to cover the popup so theres no reason to have it offset. I have a feeling it was done this way just because it was easier... or whoever made it is bad at css.
The way it was done using a grid is also just the wrong way to do this so I've cleaned up all of that as well.
The dim layer also now no longer covers the popup when the window is too small and the page is getting squished. It will fall back on covering too little of the page rather than too much.
| Before      | After      |
| ![image](https://github.com/themoeway/yomitan/assets/61125188/f0745de9-904d-4a1e-b1dd-2819f5e6a7db) | ![image](https://github.com/themoeway/yomitan/assets/61125188/b2c3325b-83e5-4e2d-aebe-1b0200faac99) |
=> Cleanup and center custom css modal

ext/css/search.css, ext/js/display/search-display-controller.js
Also disallows users to edit the size of the textbox by grabbing the handle and dragging it around which breaks the layout a bit.
=> Auto resize search textbox when removing lines

ext/css/display.css, ext/css/search.css
Fixes an issue where the search text could get so big when scanning large amounts of text that due to it being sticky it was impossible to scroll down and see all the search results.
Screenshot:
=> Make search sizing more sensible due to search textbox and query now being sticky

ext/js/pages/settings/popup-preview-frame.js
Due to the text scanner setting the theme to theme the popup based on the webpage when the body theme is set to auto, this causes the theme override for the search text in the settings page for the popup preview to be updated to the wrong theme when the search text is edited because the popup preview's "page theme" is always light due to it being 0% opacity.
This change makes search text on the popup preview get themed correctly after editing. The popup preview frame sets its own theme back to what it should be after the text scanner tries to mess it up.
This should all happen before the next draw of this element so there shouldnt be any flickering between themes.
=> Update theme after search update in popup preview

ext/js/display/display.js, ext/search.html
Due to something weird with sticky headers, our alt + scroll feature to jump to entries ended up offset on the search page. Fixing this requires adding an offset for the height of everything above the sticky header.
There was already some code for this that was unused so I just repurposed that (`#navigation-header` was removed in 2e3169f6).
`target !== 0` check is to make it so when using alt + scroll back to the top entry, it shows the elements above the sticky header instead of scrolling down slightly and hiding them.
HTML change is just adding `<div id="above-sticky-header"></div>` but git makes it messy due to the indentation change.
=> Fix alt+scroll offset from elements above sticky header

ext/data/schemas/options-schema.json, ext/js/display/display-audio.js, ext/js/media/audio-downloader.js, ext/js/media/media-util.js, ext/js/pages/settings/audio-controller.js, ext/templates-settings.html, types/ext/audio-downloader.d.ts, types/ext/settings.d.ts
In some cases the vast majority of commons audio for a language is not from lingua libre but in the format `en-example2.ogg`, which seems to me to come from users recording audio for wiktionary in an outdated way. Sometimes the filenames also have a region code like `en-us-read.ogg`.
=> Add wiktionary commons audio source

ext/css/display.css
Fixes #1154
When the popup is scrolled to the very bottom and you continue to scroll this is overscroll. The default overscroll behavior is to start scrolling the parent scrollbar (in this case the parent page outside the popup) after the focused scroll element is at the bottom.
For the yomitan popup this doesn't make sense. Setting it to contain makes it so overscroll will do nothing and not propogate to the parent page.
(This change doesn't actually limit itself to the popup but all of our scrollable settings modals already use `overscroll: contain` anyways so theres no conflict)
=> Set overscroll to contain for popup

ext/css/popup-preview.css
I saw that the color was a bit hard to read in dark mode, so I just updated it to use the example text color in popup-preview.css.
I don't know if I did this right, but it seemed to work for me... (light and dark mode works as intended for me)
Before:
After:
Light mode:
=> Change placeholder info to different color in dark mode

ext/js/language/text-scanner.js
Fixes #1166
Themecontroller doesnt actually need to be prepared here. `computeSiteTheme` doesn't use any of the prepared values.
=> Remove preparing themecontroller on parent page to avoid css collisions changing themes on the parent page

ext/js/language/translator.js
Theres also a place for this when searching kanji but I've opted to not add this check there since it should be irrelevant.
=> Override Search text with non-Japanese characters when language is not Japanese

ext/js/language/en/english-transforms.js
Deinflecting phrasal verbs (like `looked something up`) hasn't been working, this fixes it.
=> [en] simplify parts of speech to fix phrasal verbs

ext/js/language/en/english-transforms.js, test/language/english-transforms.test.js
This allows the `interposed object` deinflection when the object of a phrasal verb includes the words 'it' or 'one'.
=> [en] fix phrasal verbs with interposed 'it' or 'one'

docs/making-yomitan-dictionaries.md
=> Add Docs Explaining Adding Dictionary CSS Files

ext/css/display.css, ext/data/schemas/options-schema.json, ext/js/data/options-util.js, ext/js/display/display.js, ext/search.html, ext/settings.html, test/options-util.test.js, types/ext/settings.d.ts
This seems to be causing more trouble than good and breaks some use cases we were unaware of so I'm making it `false` by default.
Also renaming `Window` to `Search Window` in settings. `Window` is way too vague and I think users would have trouble finding the settings here or understanding what they do.
=> Add option for sticky search header

ext/js/display/search-display-controller.js
Fixes #1182
On android it is impossible for a textarea element to show the "Go" or "Search" button on the keyboard instead of the newline. It requires having an input element and doing so would break the multiline capabilities of the search box.
The android newline button also does not send any keycode but it does send enter as the key name and that can be intercepted.
Tested on Firefox android and Kiwi browser.
=> Allow enter button to search on android

test/playwright/visual.spec.js
from the playwright artifacts:
<details>
</details>
=> Playwright: Enable Advanced Settings and Capture Full Settings Page

README.md, docs/supported-languages.md
I feel like the supported languages doc could be improved here. And maybe it should go in the readme instead (under a `details`)?
=> Add Multilang Support Docs

ext/js/display/search-main.js, ext/js/dom/document-focus-controller.js
Fixes #1192
Due to the changes where pages are hidden until the load finishes this broke autofocus on the search bar. Browsers dont allow hidden elements to be focused. It needs to be explicitly focused after the page is unhidden.
Also removing the focus on prepare since the search page was the only page that used it.
=> Focus document focus controller element on the search page after body is unhidden

CONTRIBUTING.md
[discord](https://discord.com/channels/617136488840429598/1081538711742844980/1260800390434132039)
=> Update CONTRIBUTING.md with instructions on how to load unpackaged build into Chrome

docs/permissions.md, ext/permissions.html
=> Add contextMenus permission

ext/data/schemas/options-schema.json
Directly user facing settings must be added to the required properties or they will not be updated in the settings page when they are unset.
=> Fix font settings defaults not appearing in settings ui

ext/js/pages/settings/backup-controller.js
Occurs when default theme and currently selected theme do not match. For example using a dark theme browser with light theme selected then pressing "Reset Settings" would not re-render the page as dark theme.
=> Fix setting page theme not updating when reset button is pressed

ext/js/language/language-descriptors.js, types/ext/language-descriptors.d.ts
Normal everyday Tagalog does not use diacritics, so Yomitan fails to find any match for words which has diacritics in the dictionary. According to https://en.wikibooks.org/wiki/Tagalog/Lesson_13:
> Diacritics are normally not written in everyday usage, be it in publications or personal correspondence. The teaching of diacritics is inconsistent in Filipino schools and many Filipinos do not know how to use them. However, diacritics are normally used in dictionaries and in textbooks aimed at teaching the languages to foreigners.
Needs to be followed by diacritics removal at the dictionary level (e.g at [KTY](https://github.com/themoeway/kaikki-to-yomitan))
=> [tl] Add diacritics removal preprocessors

docs/development/npm-scripts.md, package.json
#1206 
- Remove JSON test from `test:static-analysis`
Fix duplicate JSON test issue on GitHub Actions. Not sure if we want to keep the current command and make a new command without the JSON test for running on GitHub Actions only.
=> Remove JSON test from static analysis

ext/js/accessibility/google-docs-util.js, ext/js/dom/document-util.js, ext/js/dom/text-source-generator.js, ext/js/language/text-scanner.js, test/document-util.test.js, types/ext/document-util.d.ts
Firefox's implementation of `Range.getClientRects()` does not match Chromium when text contains certain unicode combining characters and cannot be relied upon.
Fun 12 year old bug report: https://bugzilla.mozilla.org/show_bug.cgi?id=816238
This was previously handled in Yomichan but 5 years ago it was removed in ea9c5ad86794db44eda32e735b8aa22c5eb7726e. Japanese text and Japanese combining characters do not have this issue but some other languages do.
Fixes #1002
=> Fix Firefox scanning when some combining characters are present

ext/css/display.css, ext/js/display/display.js
This allows users to modify css of things without using `!important`.
=> Fix Overly Broad Font Family Selector

ext/css/material.css
Fixes #1238
The sticky header uses z-index 1000 and this needs to display over it.
=> Fix audio menu z-index

ext/js/app/popup.js
The invoke is guaranteed to fail if anything in this if isn't true. And that state occurs on every page load and frequently when scanning with a popup (maybe every 5-10 scans).
=> Prevent popup scaling from throwing errors constantly

ext/js/dictionary/dictionary-importer.js, ext/js/pages/settings/dictionary-import-controller.js, test/database.test.js, types/ext/dictionary-importer.d.ts
=> show downloading dictionary in steps when importing from URL

ext/css/settings.css, ext/settings.html
Also clarifies that it only applies to japanese when japanese is selected.
=> Hide "Search text with non-Japanese characters" when language is not Japanese

ext/css/display.css
This can create a lot of clutter (ex: #1236).
Before:
After:
=> Remove disambiguation prefix and suffix from css

ext/css/search.css
Justification: the font is already set in `material.css`.
This fixes an issue where the user-selected font is not displayed in the Yomitan search page. ([discussion](https://discord.com/channels/617136488840429598/1081538711742844980/1265454716331229184))
=> Remove Hardcoded `font-family` in `search.css`

ext/js/pages/settings/dictionary-controller.js, ext/templates-settings.html
=> Add Stats in Dictionary Details

ext/css/display.css, ext/popup.html
This is a simple fix to #1257. It properly contains overscroll in the popup (which was the point of #1155), but leaves it untouched in the search page allowing the user to navigate back/forward using two-finger scrolling. 
Tested in Firefox 128.0.2
=> Only contain overscroll in popup

ext/js/background/backend.js, ext/js/pages/settings/anki-deck-generator-controller.js
Fixes a regression causing the anki note generator to fail downloading audio. This regression was introduced in #1152 and snuck in primarily through changes made in #1129 which did not cause any direct issue.
Also added a log for when audio fails to download. This never triggers when the user does not have the `{audio}` in their card template.
=> Fix note generator audio

ext/css/search.css, ext/search.html
Fixes #1258
How it looks now (parser setting is hidden for users who have not set up mecab parsing):
=> Move search parser option under settings modal

ext/css/settings.css, ext/data/schemas/options-schema.json, ext/js/data/options-util.js, ext/settings.html, test/options-util.test.js
The base settings are reasonably chosen and only includes basic settings as is expected.
The advanced settings however, include both advanced settings as well as some settings that we should not expect even advanced users to use. These types of settings should not be considered "Advanced settings" and should be split out entirely.
Ive created "Debug settings" for this and only things that should almost never be touched by users should be included here. This toggle is only shown when advanced settings are enabled. Possibly this toggle shouldnt even be on the settings page and could be hidden away even further on the info page or something but I think it looks reasonable as I have it here.
The settings Ive put under debug for now isnt anything definitive. Theres probably more but just a …
=> Add toggle for debug settings

ext/css/settings.css, ext/js/language/translator.js, ext/js/language/zh/chinese.js, ext/settings.html
Fixes #1283
The entire CJK block is searched for this so the logic already applies and theres no need for an extra setting.
=> Expand "search non-Japanese characters" to Chinese and Cantonese

ext/css/display.css, ext/js/display/display-generator.js
Fixes #1262
Prevents pitch accent styles settings from touching IPA appearance.
Opted not to hide the setting for non-jp languages since theres some usage of pitch dicts in other languages and I'd rather not make the call of which languages this should apply to at the moment.
=> Disconnect IPA text and "Downstep notation" appearance setting

ext/js/dom/dom-data-binder.js
Regression introduced in #1270 (ecd9ffc3).
The newly introduced `'element'` type for dom data binder to update things which are not any type of input (checkboxes, text inputs, etc) can cause an infinite loop when updating the value.
There is a potential ping-pong between https://github.com/themoeway/yomitan/blob/ecd9ffc3d1965c4835686b814cbae8309ad0f398/ext/js/dom/dom-data-binder.js#L149-L168 and https://github.com/themoeway/yomitan/blob/ecd9ffc3d1965c4835686b814cbae8309ad0f398/ext/js/dom/dom-data-binder.js#L211-L216
When the value is updated by one of them, the other triggers, updating it again, triggering the other, and so on. This can occur any time the dictionary aliases in the settings page are updated, including when it is initially loaded.
I've added a guard against `'element'` …
=> Fix infinite event listener ping-pong destroying settings page

ext/js/background/backend.js
Users probably almost never need to see this, it may trigger too often when a user is adding uncommon words, and the error on the extension can be annoying (#1307). Changing this to a warning also puts a warning symbol on the extension icon so I've opted against that as well.
Not using `log.log` here since I want the full error details of `log.error` to be kept (`log.log` just aliases `console.log`).
=> Reduce anki audio error level to log

.github/workflows/broken-links.yml, .lycheeignore, README.md
Broken link checker keeps failing for forvo even though it works when we manually check it. Let's ignore it I think forvo is blocking requests from GH
Reference: https://github.com/lycheeverse/lychee-action?tab=readme-ov-file#excluding-links-from-getting-checked
=> Add forvo to lycheeignore

.github/workflows/scorecard.yml
v2.4.0 was broken for supply-chain dependency scanning. Not sure what the reason is and I couldn't figure out why.
The installation instructions for `scorecard-action` still use 2.3.3 so I figured maybe it's not stable/mature enough to use via a GH workflow
Run
https://github.com/themoeway/yomitan/actions/runs/10479905710/job/29026505322
=> Revert scorecard version

ext/issues.html, ext/permissions.html, ext/welcome.html
Fixes #1327 .
Firefox does not allow to go to any priviledged (`about:`) pages without manually typing it in the address bar.
=> Fix links to Extension Settings not working on Firefox

ext/js/pages/settings/dictionary-controller.js, ext/js/pages/settings/dictionary-import-controller.js
Currently works for KANJIDIC and BCCWJ.
In `recommended-dictionaries.json`, Jitendex has its title hardcoded as `Jitendex`, but the title of it after installed from the recommended section is `Jitendex.org [2024-08-11]`. Don't know if we have control over the title of Jitendex,
Fixes #1333
=> Disable download button when dictionary is already installed

ext/data/schemas/options-schema.json, ext/js/app/frontend.js, ext/js/background/backend.js, ext/js/data/options-util.js, ext/js/display/display.js, ext/js/dom/dom-text-scanner.js, ext/js/dom/text-source-generator.js, ext/js/dom/text-source-range.js, ext/js/language/text-scanner.js, ext/settings.html, test/options-util.test.js, types/ext/dom-text-scanner.d.ts, types/ext/settings.d.ts, types/ext/text-scanner.d.ts
=> Whole word scanning

ext/js/pages/settings/dictionary-import-controller.js
It is already validated that this wont trigger on something insane due to this being attached to a `click` event listener. Explicitly checkout for PointerEvent creates issues for users tabbing around and for users trying to use touchscreens.
Fixes #1350
=> Remove unneeded PointerEvent check in _onRecommendedImportClick

ext/js/display/search-display-controller.js
Fixes #1346
Paste on everywhere (except on input field) will update the search input and trigger search. 
Should this be default behavior or we need to make it as an option?
=> Paste on search page will trigger search

ext/js/background/backend.js
Currently `anki.enabled` is always `false` if Yomitan is disabled, which makes Anki not working when using search page
Any problem if we keep Anki enabled even though Yomitan is disabled?
Fixes #1008
@Kuuuube thoughts?
=> Allow add Anki cards on search page when Yomitan is disabled

ext/js/pages/settings/dictionary-import-controller.js
- The download queue does not work because the `_importDictionaries` call is not awaited so the function ends immediately without checking any other item in queue.
- When the dictionary is in queue, disable its download button. Currently, if the user reopens the recommended dictionary modal, the download button is still active.
=> Fix recommended dictionary download queue

ext/css/popup-outer.css, ext/data/schemas/options-schema.json, ext/js/app/theme-controller.js, ext/settings.html, types/ext/settings.d.ts
=> Add `None` Popup Shadow Option

.eslintrc.json, .vscode/settings.json, ext/data/recommended-dictionaries.json, ext/data/schemas/recommended-dictionaries-schema.json, ext/js/pages/settings/dictionary-controller.js
Resolves #1402
I do wonder if there's something that can be done so the dictionaries themselves are sorted by name instead of by description.
=> Enable `jsonc/sort-keys` on `recommended-dictionaries.json`, Update `recommended-dictionaries-schema.json`

.github/workflows/codeql.yml
Fix by removing duplicate `permissions`
=> Fix CodeQL Workflow

ext/js/language/ja/japanese-transforms.js, test/language/japanese-transforms.test.js
- Remove `causative-passive` form, basically it's just `short causative -> passive` form.
- Avoid conjugating short causative with さす ending with passive form (食べさされる is wrong)
=> Refactor `short causative -> passive` form

ext/js/data/anki-note-data-creator.js
Frequency of <=0 messes up frequency calculation so these values should be ignored.
=> Guard against frequency dicts with values of 0 or less

ext/js/dom/text-source-generator.js
UTF32 characters take up two indexes in JS strings and the sentence parser was indexing the string directly causing an incorrect offset to be applied to the sentence. This causes the `{cloze-prefix}`, `{cloze-body}`, and `{cloze-suffix}` handlebars to select the wrong text.
Converting the text to an array before parsing combines UTF32 characters into a single index.
Discovered on this page: https://learnjapanese.moe/texthooker.html. It has a UTF32 emoji character in the top right (🚫) which gets pulled into the sentence parser.
=> Fix UTF32 characters breaking sentence parser due directly accessing string array indexes

ext/js/dictionary/dictionary-importer.js
when validating a dictionary as it is being imported, if a syntax error is encountered, a message would describe the syntax error that has occurred. To provide clarity, the syntax error message will now also describe the file in which this error occurred.
=> syntax error message made more verbose

ext/js/data/anki-note-data-creator.js
=> Fix frequencies missing value to push to array

test/playwright/visual.spec.js
=> Add screenshot of welcome page in visual test

ext/js/display/display.js
Adds some performance markers to allow for some performance improvements that will come in further PRs.
=> Begin to add performance marks

ext/js/templates/anki-template-renderer.js, test/data/anki-note-builder-test-results.json
=> Add term tags to `{tags}` Anki field

ext/css/search.css, ext/js/display/search-display-controller.js, ext/search.html
=> added cancel button in search page that clears the query

ext/popup.html
Fix #1343
Change anchor element target to navigate to the dictionaries settings without opening a new tab.
=> Fix No Dictionary Enabled settings link opening in a new tab (#1343)

ext/templates-modals.html
Add helper text to the Recommended Dictionaries modal that links to kaikki-to-yomitan, for users that don't want English dictionaries. #1428
After:
=> Add helper text & link for Non-English dictionaries (#1428)

ext/info.html, ext/quick-start-guide.html, ext/welcome.html
Add wiki link to welcome.html
Change text to welcome on quick-start and add info page link
closes #1508
1) Info.html now has a link to the quick start and wiki
2) welcome.html now has a link to the wiki
3) quick-start-guide.html now has a link to info and changed the text to the welcome page to be consistent. This is in order for the user to be able to navigate back to the info.html page
=> Add quick start and wiki links to info.html

ext/js/display/query-parser.js
Addresses https://github.com/yomidevs/yomitan/issues/1370. When a parser is on, it will still parse words putting spaces in-between, which is not good for the user, but the result we expect. When all parsers are off, it will now only update text and not parse.
Before, Parser On:
Before, Parser Off:
New Code, Parser On:
New Code, Parser Off:
=> Search page displays queried sentence even when parser is off.

ext/js/data/anki-note-data-creator.js
=> Fix UTF16 and UTF32 characters breaking cloze data due to the use of substring

ext/js/display/display.js, ext/js/display/query-parser.js, ext/js/language/text-scanner.js, types/ext/text-scanner.d.ts
Fixes #1280.
Needs more testing and probably some cleanup. This should also allow removing the option for scanning with middle click in favor of the user adding a scanning input option containing middle click (or any mouse button they want).
=> Allow scanning without moving mouse from clicking

.github/workflows/playwright.yml, .github/workflows/playwright_comment.yml, playwright.config.js
Confirmed to work: https://github.com/MarvNC/yomitan/pull/10#issuecomment-2443372684
=> Use Playwright Report Summary Action

ext/js/language/language-descriptors.js
Replaced the 2nd. person plural indicative (czytacie) with an infinitive (czytać) in Polish example.
=> Change Polish Example to an Infinitive

ext/js/language/language-descriptors.js
Changed examples for all languages to infinitives. Data from English Wiktionary.
=> Change Examples to Infinitives

ext/js/data/options-util.js, ext/js/language/language-descriptors.js, ext/js/pages/settings/dictionary-controller.js, ext/js/pages/settings/dictionary-import-controller.js, ext/js/pages/settings/profile-controller.js, test/options-util.test.js, types/ext/settings-controller.d.ts, types/ext/settings.d.ts
Fixes #1488
Preserve dictionary position and settings across all profiles after update (except `title`)
=> Update dictionary will preserve its settings

ext/js/app/frontend.js, ext/js/dom/dom-text-scanner.js, ext/js/dom/text-source-range.js, ext/js/language/text-scanner.js, types/ext/text-scanner.d.ts
Fixes #1526 
The html for the example text upon loading the settings page
```html
<div class="example-text-container">
<input type="text" class="example-text example-text-input" id="example-text-input" lang="en" hidden>
<span class="example-text" id="example-text">rea</span>
</div>
```
In a normal operations, when a user clicks on the example text, the `<span>` becomes hidden and the `<input>` becomes visible. However, all search is done _through_ the value set in the `<span>` class.
We have the class `PopupPreviewFrame` (plus an obscure css rule) that manages the state between the `<input>` and the `<span>` elements.
When search is triggered, Yomitan searches for value inside `<span>`. Since the span is hidden while editing the example text, the element would normally be skipped to …
=> Fix example text popup not updating correctly when scan resolution is set to `word`

ext/js/pages/settings/profile-controller.js, ext/js/pages/settings/settings-controller.js
Fixes #1556
Let's call editing profile index `x` and deleted profile index `y`
Currently we does not handle:
-  `x < y`: The default profile and editing profile will be reset to the first profile, however when reload the page, it still has the value before reset. Additionally, the radio button does not represent the default profile correctly. Calling `_setProfileIndex` with the same `x` value will resolve this.
- `x > y`: The editing profile index is not shifted up, therefore it moves into below profile. When the editing profile is the last index, it will cause index error, and we cannot add more profiles after that. The issue happens because when we add a profile, the editing profile index is set to last index.
List indexes are also updated correctly after deletion.
=> Set editing profile index correctly when deleting profile

ext/js/pages/settings/dictionary-import-controller.js
Additional change to #1553.
Since we are preserving the alias when updating dictionaries, for dictionaries which have new title for every new version, the alias does not match the title after updated. For example:
Therefore, we want to update the alias if it is the same as the title (not yet set by the user), and preserve the alias otherwise.
=> Update dictionary will update alias if alias is the same as previous title

ext/info.html, ext/js/pages/support-main.js, ext/support.html
=> Add support page

ext/css/settings.css
`white-space: nowrap` is the equivalent of `white-space-collapse: collapse` and `text-wrap-mode: nowrap`. 
`white-space-collapse: collapse` is not needed here and on firefox, causes newlines to display as spaces.
=> Fix "Import dictionaries from URLs" textarea not showing newlines on firefox

ext/js/pages/settings/dictionary-controller.js, ext/js/pages/settings/dictionary-import-controller.js, types/ext/dictionary-controller.d.ts, types/ext/settings-controller.d.ts
Closes #1557
~~When enqueue a dictionary, hide its update button.~~
~~Also refactor dictionary update and delete behavior, only allow 1 queue to run at a time.~~
~~- If update queue is running then disable all delete buttons.~~
~~- If delete queue is running then hide all update buttons.~~
=> Allow queueing dictionary update & delete together

.github/workflows/publish-firefox.yml
Untested. Zipball filename verified to use `reponame-tag.zip` from https://github.com/robinraju/release-downloader/blob/main/src/release-downloader.ts#L238.
=> Add sourcesZipFilePath to publish firefox

ext/templates-modals.html, ext/templates-settings.html
=> Add TTS Anki Warning

ext/data/recommended-settings.json
Closes #1573 
Adds two settings to languages with spaces:
- Set parsing.enableScanningParser to false to turn off internal parser
- Set parsing.termSpacing to false to remove added spaces between parsed words
=> Add turning-off of parser for languages with spaces in recommended settings

ext/js/display/query-parser.js, ext/js/display/search-display-controller.js
Fixes #1463
When a pattern that selects newlines is added to the text replacement patterns, it can allow queries with trailing newlines to be accepted as the longest match. This can cause some weird things in the search page UI (#1463).
=> Trim search query strings to prevent newlines expanding search page

ext/action-popup.html, ext/css/action-popup.css
=> Fixed spacing and moved tabindex in the action popup

ext/js/data/string-util.js, ext/js/display/query-parser.js, ext/js/display/search-display-controller.js
#1600 broke display of parsed words for languages with spaces. This should restore it back to how it was.
Trimming function benchmarked at 794M ops/s (compared to regex at 10M ops/s and looping at 28M ops/s).
Naming is hard, `trimTrailingWhitespacePlusSpace` is the best I could come up with... Without making the variable name a whole book.
The value for `queryInput` can be trimmed on the end normally since the only thing it does is modify what is in the search bar and not any of the parsing.
=> Fix whitespace trimming in search page

ext/js/dictionary/dictionary-data-util.js, ext/js/display/display-generator.js, ext/js/display/display.js, types/ext/dictionary-data-util.d.ts
Fixes #1484
Fixes #570
Didn't do pitch dicts since I couldn't think of what metadata would be useful there. That can be in another PR if needed.
Term dict:
Kanji dict (if kanjidic had a description it would be shown here...):
Frequency dict:
=> Show metadata when clicking on term, kanji, and frequency dictionary tags

ext/js/pages/settings/sort-frequency-dictionary-controller.js
Related #1611
This PR doesn't actually fix anything, but this should make it easy for people more knowledgeable in languages to help get this fixed.
Some dicts dont set a language tag so it will just test all words from every language in that case.
(The funky `if (Object.hasOwn(moreCommonTerms, key))` is because of this js fun: https://eslint.org/docs/latest/rules/guard-for-in)
=> Set up getFrequencyOrder for other languages

ext/js/display/display-generator.js
Due to Firefox not allowing click events to fire for elements that are not visible, this wasn't working.
For freq tags there are two `tag-label` elements at different spots in the hierarchy where events are attached. One is visible, one is hidden. The parent element of these contains the tag details data. Firefox gets the one which is visible and fails to find the correct tag details to display in the notification. For whatever insane reason, Chromium does send through click events on invisible elements so it ends up getting the other `tag-label` element which did have the frequency count data on it. I'm also not sure why we have two tag labels to begin with and why theres one that is hidden but I'm not going to dig into that here.
This PR just makes it so the data appears in both places.
=> Fix firefox not showing Frequency Count when clicking on freq dict tag

ext/js/display/search-display-controller.js
If there are multiple lines in the search textbox it wouldn't shrink and would look silly with no text in it but a large textbox. This makes it go back to one line when clearing the text.
=> Fix search page textbox size not shrinking when clicking clear button

ext/js/display/display-anki.js, ext/js/display/element-overflow-controller.js
Might fix #922, #836, #1480
I can't say for certain this is all of the issue but I wasn't able to find anything else in my testing.
=> Fix leaking memory due to not improper cleanup of references to detached nodes

ext/js/display/element-overflow-controller.js
Fixes #1658
Regression from #1645
Don't need to call `this._dictionaries.clear();` since the number of `this._dictionaries` instances are equal to the deepest level of popup has been spawned. Unlike event listeners, it does not have cumulative effect no matter how many times the user scans.
=> Fix collapse dictionary not working

.eslintrc.json, ext/js/language/eo/esperanto-transforms.js, ext/js/language/language-descriptors.js, test/language/esperanto-transforms.test.js
Adds language transforms for Esperanto. Covers all sorts of de-inflections and word constructions from common affixes that Wiktionary doesn't have. I've been testing it for a week now, and it's been working great.
=> add esperanto transforms

ext/js/pages/settings/dictionary-controller.js, ext/templates-modals.html
Somewhat of a fix for #1092.
Adds a stripped down synchronous version of `_updateEntries` that also resets the scroll position. 
Moving dicts doesn't require all of what `_updateEntries` uses since the number of dicts, dict names, dict contents, etc should never be changed in a move.
Intentionally not adding the scroll position reset to `_updateEntries` since during other operations there can be other errors that the user needs to see at the top of the modal body.
=> Make dict moving faster and save scroll location

ext/js/display/display.js
Regression added in #1670
Causes the popup to not render any contents.
Considering `performance.mark` is not linted or checked in our code (if possible that would be nice to have) maybe we need to make wrapper functions for this to handle errors without blowing up the entire extension.
=> Fix bad performance.mark names causing performance.measure to fail

.eslintrc.json, dev/bin/schema-validate.js, dev/dictionary-validate.js, ext/js/app/frontend.js, ext/js/app/popup.js, ext/js/background/backend.js, ext/js/comm/cross-frame-api.js, ext/js/core/promise-animation-frame.js, ext/js/core/safe-performance.js, ext/js/dictionary/dictionary-database.js, ext/js/display/display-generator.js, ext/js/display/display.js, ext/js/language/text-scanner.js, ext/js/language/translator.js, ext/js/pages/settings/dictionary-controller.js, ext/templates-modals.html
Fixes merge conflicts from #1677
History here looks a little funky but when it's actually merged into the PR only 65ec09da12cda06e90bb18769d2ed44fc901a61f and e80b3c34400aa1e4933abe2879df650cc9aa6f2d should show since master already has the others.
=> safePerformance for performance-canvas (#1487)

ext/js/display/display.js, ext/js/display/element-overflow-controller.js
Fixes #1583
https://www.loom.com/share/8237d780ca974e35bf77726415532918
=> Collapse entry will scroll back to top of entry

ext/js/data/anki-note-builder.js, test/data/anki-note-builder-test-results.json
Fixes #1558 
Not sure how to add tests or if its necessary
=> Leave url field blank when creating cards from search page

.github/workflows/publish-chrome-development.yml
Chromium can already install extensions from zip files offline without issue but updating extensions installed that way is essentially impossible. With a consistently signed crx it is possible for users to both install and update the extension without using the store.
We can't sign the crx with the same key as google does on the store so users wont be able to update their extension with this crx file if they previously downloaded from the store. Only the store can update the store version and only the release crx will be able to update the release crx.
It also isn't reasonable to make an action that downloads the chrome store crx and uploads that since there's no way to know when the chrome store will be updated and allow downloading the new version.
This will require adding a new secret …
=> Add chrome dev crx to releases

ext/js/data/anki-note-builder.js
`URL.canParse` is not supported by the Kiwi Browser as late as version `124.0.6327.4` so we need to avoid using the API until then.
A followup for the Kiwi community is here on their discord https://discord.com/channels/494814211579445270/494885738547249153/1322068526047166464
=> Avoid using `URL.canParse` 

.github/actionlint-matcher.json, .github/workflows/actionlint.yml, .github/workflows/auto-approve.yml, .github/workflows/create-prerelease-on-tag.yml, .github/workflows/delay.yml, .github/workflows/playwright_comment.yml, .github/workflows/publish-chrome-development.yml, .github/workflows/publish-chrome.yml, test/data/json.json
GitHub actions workflows are incredibly dangerous from a security perspective, and in particular it's really easy to write vulnerable bash scripts in them. `actionlint` checks a number of things (including running shellcheck on all `run` scripts within the workflows). This will hopefully be a good start to securing our workflows a bit more.
=> Add actionlint & fix detected issues

.github/workflows/playwright_comment.yml
In https://github.com/yomidevs/yomitan/pull/1676 we merged a change that completely broke all popups.
Our E2E testing (playwright) did detect the issue, but its output was ignored.
My analysis is that it was ignored because the output of `playwright-report-summary`:
1. does not make a clear visual differentiation between flaky tests and failures, requiring the user to carefully analyze the output
2. does not link to the report artifact, making it high friction for the user to actually check the report to see what changed
3. does not have a clear call to action instructing the user what they should do
I believe it is better to have our own custom comments (basically revert https://github.com/yomidevs/yomitan/pull/1543 and improve the original comments a bit to properly differentiate …
=> Improve playwright comments

ext/js/dictionary/dictionary-database.js, test/utilities/database.js
The #1487 performance PR introduces a dictionary worker, which means there's an extra open handle to our IndexedDB db. This prevents deletion of the DB as it will result in a blocked event. So we need to clean up the worker here.
=> Fix broken dictionary collection import

.github/workflows/ci.yml
Example failure: https://github.com/yomidevs/yomitan/actions/runs/12527643958/job/34941425160
Not a real issue, just makes the CI look broken on master
=> skip bench on merge_group as it's not supported

ext/js/core/utilities.js, ext/js/data/anki-note-builder.js
Prevents malformed css from making it to Anki. Browsers already sanitize css when adding it to the DOM so there's no need to add sanitization there.
=> Sanitize css before sending to Anki

.github/workflows/playwright.yml, .github/workflows/playwright_comment.yml, playwright.config.js, test/playwright/visual.spec.js
* Break out the popup tests into completely standalone tests as opposed to reusing the same test/browser. This allows parallelizing it.
* Shard the playwright tests into shards on CI/CD.
We have a quota of 20 total concurrent jobs, so we could potentially increase the number of shards introduces by this PR (5) but it may come at the cost of causing other jobs to get queued since we have no way of specifying priority between jobs, which may not be the right tradeoff. Also, separately, we could increase the number of workers in playwright from 1 to 2, but will need to observe the stability within GitHub actions runners. It would be appropriate to tune further.
Previously, since we were using a single browser, one of the tests (test 6) was never able to clear its popup from the screen …
=> Speed up playwright (pt2: full parallelization)

ext/js/core/utilities.js
I got the supported versions for this wrong in #1722. This check should not be needed.
=> Make sanitizer fail entirely on any errors

.github/workflows/playwright.yml, .github/workflows/playwright_comment.yml
Fix a couple issues introduced by #1720
=> Fix playwright

test/playwright/integration.spec.js
Fix the occasional flaky Anki playwright test by ensuring the settings page is ready for actually loading in the dictionary.
=> Fix flaky Anki playwright test

test/playwright/visual.spec.js
A few more minor playwright performance improvements:
* Reduce the viewport size on popup screenshots so they execute faster (and it also makes the results easier to read)
* Split the two big dictionary loads into separate tests so they can be executed in parallel
This is expected to change playwright results since the viewport size is different, and also the number of remaining dictionaries after the swedish delete is different (0 instead of 1)
=> More minor playwright performance improvements

tag.sh
We should sign/annotate our tags so it's clear who did the tag. See #1687 as well.
Eventually we may be able to modify our CI to require the tag to be signed before creating the release, which would give us some really nice cryptographic guarantees about the release validity all the way to the store essentially.
=> Modify tag.sh to sign tags

test/playwright/visual.spec.js
We can see in https://github.com/yomidevs/yomitan/pull/1740 that there seems to be some flakiness with playwright results on popups.
I removed this `steps` in one of the playwright performance PRs since I thought I had it working in a non-flaky manner, but it's possible this is still required to bring it from 99% to 100%, so this will attempt to reintroduce it.
=> Try and reduce playwright flakiness

ext/data/schemas/dictionary-term-bank-v3-schema.json, ext/js/display/structured-content-generator.js, types/ext/structured-content.d.ts
Allows the `details` element to be opened by default.
I'm creating a new layout for extra information in [kaikki-to-yomitan](https://github.com/yomidevs/kaikki-to-yomitan) like `etymology`, `head-info`, `synonyms`, `morphemes` etc. So this will be useful for having entries like `morphemes` open by default.
=> add open attribute for details

ext/js/pages/settings/anki-deck-generator-controller.js
Apparently some dicts have a `\r\n` in them and even after removing the `\n`, the browser inflates it back to `\r\n` when saving.
=> Remove \r from anki note generator tsv

ext/js/core/utilities.js, ext/js/data/anki-note-data-creator.js
Much more robust than the previous regex solution.
Related: #1500 #1726
=> Fix Anki css scoping breaking due to Anki shipping with incredibly out of date Chromium version (112)

ext/data/schemas/options-schema.json, ext/js/data/options-util.js, ext/js/display/display.js, ext/js/language/text-scanner.js, ext/js/pages/settings/scan-inputs-controller.js, ext/templates-settings.html, test/options-util.test.js, types/ext/settings.d.ts, types/ext/text-scanner.d.ts
Fixes #1755
Fixes #1043
This option makes it so the user has to press and hold for a specified amount of time before touch release or touch tap will allow the popup to appear. Pressing and releasing too fast will not allow a popup.
Only lightly tested.
=> Add minimumTouchTime setting to scanning inputs settings

ext/js/language/language-descriptors.js, types/ext/language-descriptors.d.ts
This PR adds the Welsh language support.
https://en.wikipedia.org/wiki/Welsh_language
The welsh language uses capitalisation and has an alphabet with 29 characters in the alphabet (although several are diagraphs), from the Latin alphabet: https://en.wikipedia.org/wiki/Welsh_orthography
The language supports Majuscule forms, Titlecase forms and Miniscule forms. There are 8 diacritics which are primarily used for vowels, made up of letters from the Latin alphabet.
=> Add Welsh support

ext/js/language/text-scanner.js
On some sites, there is an issue where touching too quickly will show the popup but then it will instantly disappear. This only happens when the popup is triggered on a touch end (touch release an touch tap).
Adding `preventNextMouseDown` prevents erroneous clicks from being registered after the touch release that make the popup close itself.
This implementation is similar to `_searchAtFromTouchStart` right above it.
=> Apply preventNextMouseDown for touch end to prevent instantly closing popup 

ext/js/dom/dom-text-scanner.js, test/data/html/dom-text-scanner.html
Fixes #1636 and #1648
Basically if you click the first word of a div
```html
<div>
<div>Clipboard Monitor</div>
<span>query</span>
</span>
```
the DOMTextScanner starts the scan right before `<span>query</span>`. When `extractSentence` is run and it goes backwards to `<div>Clipboard Monitor</div>`, `this._newlines` is set to `1` for being a div but it doesn't hit this  [`if (this._content.length > 0)` condition](https://github.com/yomidevs/yomitan/blob/master/ext/js/dom/dom-text-scanner.js#L344) which causes the `\n` not to be added to `this._content`
The fix is actually fixing two issues:
1. `setStartOffset` with `stopAtWordBoundary = true` terminates outside the div of the word if the word is at the beginning of the div.
```html
<div class="outer">
<div class="inner">word</div>
</div> …
```
=> Fix setStartOffset stopAtWordBoundary behavior to terminate at the beginning of current div

.github/workflows/playwright.yml
Fixes playwright test failing.
https://github.com/awalsh128/cache-apt-pkgs-action/commit/5902b33ae29014e6ca012c5d8025d4346556bd40
=> Bump awalsh128/cache-apt-pkgs-action to version that does not use deprecated dependencies

ext/js/data/anki-template-util.js, ext/js/display/display-anki.js, ext/js/pages/settings/anki-controller.js, ext/js/pages/settings/anki-deck-generator-controller.js, ext/js/pages/settings/anki-templates-controller.js, ext/js/pages/settings/settings-main.js
Some users have thought they could use the `single-glossary` handlebars for frequency or pronunciation dicts due to them showing on the list. This removes them. It also opens the door for other handlebars for example `single-frequency` or `single-pitch-accent`.
=> Only show dictionaries with at least one term for single-glossary handlebars

ext/js/display/display.js
Only tested on Chromium. Need a tester for Kiwi.
=> Use addScopeToCssLegacy to fix dict css on Kiwi due to out of date Chromium base

ext/css/display.css
Fixes #1753 
Not going full red with the background and all since I don't think it should be too disruptive.
| Before | ![image](https://github.com/user-attachments/assets/e08c46f9-330e-4cb3-b9c5-1d4303888431) | ![image](https://github.com/user-attachments/assets/7bd14046-a97e-4bba-af93-d6bc4f99b730) | 
|--------|-------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------|
| After  | ![image](https://github.com/user-attachments/assets/980165ec-8b2f-4a57-b39d-aa3c69f68b0a) | ![image](https://github.com/user-attachments/assets/d7d0ccc5-64b4-4157-94e1-38a9e20a5060) |
=> Make anki error footer notification text red and bold

ext/css/display.css, ext/css/search.css
Fixes #1814
Fixes #1812
`content-visibility: auto;` appears to only render elements in padding when the padding comes from the element itself. Not any if its children. This shifts the padding from being provided by `--main-content-horizontal-padding` to `--entry-horizontal-padding` (which is applied to the `entry` class) on the search page.
Added `--query-horizontal-padding` to allow the search page to override the padding of that element as it had done before but without it breaking the rendering of everything on the sides.
(The element that has padding set to 0):
| Before                                                                                     | After                                                                                     | …
=> Fix cutoff indicator and audio failed X on search page

dev/data/manifest-variants.json, ext/js/background/backend.js
Fixes #1688
Tested on Firefox and Chromium. I don't see any extra permissions that are required to add this to the manifest.
How this works is if a user types `Yomitan {whatever}` in the search bar, the browser will show a suggestion (if suggestions are enabled) to search `{whatever}` in Yomitan's search page.
=> Add support for omnibox search with Yomitan

ext/js/language/ru/russian-text-preprocessors.js, types/ext/language-descriptors.d.ts
Makes the `yoToE` Russian preprocessor bidirectional.
Allows coverage for situations like:
- застегивала → застёгивала → застёгивать
- теплой → тёплой → тёплый
- вдвоем → вдвоём
=> make russian preprocessor bidirectional

ext/settings.html
Now that overwriting is less dangerous by default, the warning can be less conspicuous.
=> move overwriting warning to more-toggle

ext/js/dom/text-source-generator.js
Fixes #1044
Almost a year ago I wrote this comment https://github.com/yomidevs/yomitan/issues/1044#issuecomment-2254261520 on our shadow dom issues. Since then, Chromium has gotten `caretPositionFromPoint` into stable builds and support for the `shadowRoots` option has been added. There also should have been plenty of time for all maintained Chromium forks to get up to date with this feature.
This allows piercing any shadow root specified by the options. Firefox's implementation pierces all shadow roots by default but we aren't so lucky to get that on Chromium (the people making the w3c spec were against handling it like this https://github.com/w3c/csswg-drafts/issues/9932#issuecomment-2035004366). `_findShadowRoots` here will get us all the shadow roots within all children of the input …
=> Pierce shadowroots on Chromium using caretPositionFromPoint

ext/js/pages/settings/anki-controller.js
Yomitan attempts to automatically set up Anki card configuration for users that have note types with fields that match or are similar to the names of handlebars. As is, the set of aliases is extremely small. I've gone through many popular note types and found reasonable field names that can be aliased to help users set things up quickly.
Note that Yomitan allows dashes to be dashes, underscores, or spaces. So the alias `expression-reading` is actually an alias for `expression reading` and `expression_reading` as well.
=> Improve default anki field setup

ext/js/pages/settings/anki-deck-generator-controller.js
The previous function was ridiculous and ended up failing on some weird combinations of nested objects and arrays. Which Yomitan dicts tend to be extremely prone to creating.
Since all that is required is extracting a string for the path to media, it is much easier to flatten the entire definition structure into a string and search it with regex. No witchcraft necessary.
The media in this case only includes images or svgs contained in definitions. Audio fetching has no issue.
=> Fix finding media to inject in anki note generator

ext/js/display/search-display-controller.js, ext/js/language/ja/japanese-wanakana.js, ext/js/pages/settings/popup-preview-frame.js
The previous handling of this by using `wanakana.bind` surrenders handling to wanakana and Yomitan does not have control over when input should be converted. We have to deal with whatever bugs they have. This PR gives Yomitan back control over when conversion should be triggered.
The wanakana library also appears possibly abandoned and has not received updates in 2 years when previously it was receiving quite frequent updates (although the maintainer appears to be somewhat active still). I've created an upstream bug report anyways ([#179](https://github.com/WaniKani/WanaKana/issues/179)). Due to the tiny usage of this library's features we should probably just ditch the library entirely. But I'll leave that to another PR. The changes here are still relevant regardless.
To replicate this …
=> Fix wanakana breaking IME input when hitting a conversion containing latin characters

ext/js/dom/text-source-generator.js
=> Fall back to `caretRangeFromPoint` more aggressively to save Kiwi from being unable to scan

ext/welcome.html
Since the welcome page borrows modals also used on the settings page this is needed.
=> Add visibility-modifiers.css to welcome page

ext/js/media/audio-downloader.js
For improving the audio server API, adding a 'language' parameter to the API call would make things more organized for working with multiple languages.
I added that parameter.
=> Add 'language' parameter to audio API call

ext/js/display/search-display-controller.js
No need for it to take up extra space. The profile selector also often bumps the search page header down an extra row for mobile users which is very bad if they arent using profiles. Most of our users are probably only using one profile.
=> Remove profile selector from search page if user has only one profile

ext/css/search.css
In #1815, I removed padding on the search page. But the search header does still need padding. On mobile devices or for users the squish their search window into a small vertical sliver, it looks horrible. with everything extending into the sides.
| Before Bug | Current Master | This PR |
|----------|----------|----------|
| ![before](https://github.com/user-attachments/assets/697cdf47-3bf9-4b8e-8be1-15514a1eb75e) |   ![before](https://github.com/user-attachments/assets/0b6f8b77-654d-48a6-803b-2421cd16c06a)   |   ![after](https://github.com/user-attachments/assets/57ec8b83-4af4-44d4-a5b9-4c5578d60e10)   |
=> Add horizontal padding to search header

ext/js/pages/settings/dictionary-controller.js
Somehow this got missed in #1248
=> Add missing termMeta to dict details modal

ext/css/settings.css, ext/js/pages/settings/dictionary-controller.js, ext/templates-modals.html, ext/templates-settings.html
Fixes #1582. Tested on Firefox and Chromium.
Checking integrity is kindof pointless if it can't even check if your dicts have the expected amount of entries. 
Ideally this would be automatic but unfortunately it isn't reasonable to automatically show this when a user enters the settings page due to how long it takes to run over the entire database for the integrity check.
Also makes Unassociated Data and other check integrity data displays not a json string dump.
It may be worth pulling the `Check Integrity` button back into advanced settings instead of debug settings since especially on mobile, users often have issues with their dicts partially importing due to their device turning off or the browser hanging from battery saving. Though, this is "debugging" still.
Dict counts before …
=> Detect missing entries when dicts fail to import with `Check Integrity` button

ext/issues.html, ext/js/pages/settings/settings-display-controller.js, ext/popup.html, ext/quick-start-guide.html, ext/search.html, ext/settings.html, ext/templates-display.html
Fixes #1892
Firefox does not trigger a `popstate` event when navigating to the same anchor link twice. Chromium does (possibly violating the spec). If there is no url change from the anchor link being clicked, Firefox wont fire the event. But Firefox will still navigate to the correct spot on the page.
The anchor link handling within Yomitan intentionally set invalid anchor links (`#!` instead of `#`) to be handled by `_updateScrollTarget`. This doesn't make sense to do. There is no extra handling anywhere that makes this necessary.
It's possible in the past this was to handle scrolling to the correct position on initial page load but that doesn't work. With or without this PR. There are too many reflows and it would need to scroll the position much later than the settings controller will …
=> Use normal anchor hashes in anchor links

ext/js/display/display.js
Fixes #1376... Though strictly as the issue describes this was never an issue, it worked kinda terribly.
Before this pr, setting `Clipboard text search mode` to `Update search only` would indeed not search the word. But it would just clear the entire search so any searched definitions you had there before wouldnt show. This just makes it so nothing changes except the search bar.
Example (I searched よむ initially then copied わかる and you can see わかる is only present in the search bar while the info on よむ is still visible):
=> Don't clear existing search when clipboard is updated and `Update query only` is set

ext/js/pages/settings/dictionary-controller.js
Broke this when I was stripping down the function to make it faster (#1671). Copy paste from the `_updateEntries` code into `_updateCurrentEntries` (only used for moving dicts).
When moving dicts the update button appears on any dict that has an update url set instead of dicts that actually have been checked for an update, and have an update.
=> Pull update url from existing entries when moving to prevent update button from appearing when it shouldnt

ext/js/pages/settings/dictionary-controller.js
Borrows from #1902. Probably best to merge that one first. Could have conflicts as well.
=> Preserve integrity check details when moving around dictionaries

ext/css/display.css
Fixes #1917
The container size seems to change strangely sometimes depending on the font. So `border-bottom` isn't great to use as an underline. Browsers have more info on fonts that can help position the underline if we use a real underline with `text-decoration`.
Using 1/15 the font size for the offset since that appeared to match well to what it was before on chromium (firefox was a bit larger offset) with the some default fonts.
Example:
=> Fix underline on kanji headword characters jumping around with different fonts

ext/js/data/string-util.js, ext/js/display/query-parser.js
When copy-pasting a lot of text with newlines in it, it can be hard to quickly find a certain spot in the text since it would be reformatted to remove the newlines. The newlines should be kept. But it seems reasonable to condense them.
#1600 and #1625 both overdid the trimming. In order to fix #1463 all that was really required was to trim the final piece of text...
Tested with Japanese and English (does not break spacing in languages with spaces).
Before:
After:
=> Partially preserve newlines in search queries on search page

ext/js/language/text-scanner.js
Fixes #1931
Since the downstream code from this function has no way of knowing this input came from a keypress (and it's probably not great to make another param), synthetic mouse events should not be blindly sent through if they do not contain any modifiers matching those set in the user's scanning settings.
=> Check if modifier is set when scanning from keypress without move before pushing through synthetic mouse event

ext/js/language/ja/japanese-wanakana.js, test/japanese-util.test.js
nya nyu nyo would become んや んゆ んよ from missing handling of the single `n` case with `ny`.
=> Fix ny becoming んy

ext/js/display/search-display-controller.js
It's a bit strange to type something ending in `ん` with a single `n` on the end and then see the search happen but `n` doesn't become `ん`. This doesn't matter for strictly usability (Yomitan searches the `ん` anyways) but it feels weird. The user searching can be taken similarly to the user acknowledging that composing is finished and converting everything should be fine.
With this change for example typing `どn` and searching will make it automatically become `どん` in the search bar.
Clicking in the middle of the search text, searching, then hitting backspace or typing and having the text cursor end up back where you clicked before your searched is also weird. And especially annoying when trying to quickly wipe the search box (ctrl + shift + backspace).
=> Update search query text when searching and set cursor to end of line

ext/js/display/display.js, ext/js/display/search-display-controller.js, ext/js/language/ime-utilities.js, ext/js/language/text-utilities.js, ext/js/pages/settings/popup-preview-frame.js
Android browsers often pretend to be composing when typing. Having a blanket filter for composing doesn't work here.
On mobile chromium browsers we can fairly easily check if theyre pretending to be composing by checking if they're "composing" a single alphabetic letter.
On firefox mobile, this doesn't work so it's excluded from this check.
=> Handle mobile browsers pretending to be composing

ext/js/display/search-display-controller.js
Fixes all languages getting Japanese IME text substitutions instead of just Japanese on search page.
Regression introduced in #1875
=> Check for wanakanaEnabled on search page before applying kana conversion

.lycheeignore
Foosoft has implemented [go-away](https://git.gammaspectra.live/git/go-away) to the anki-connect repo. Lychee seems to get flagged by this and always fail.
=> Add foosoft ankiconnect repo to lycheeignore

.lycheeignore
It is linked without the slash somewhere so link checker is still breaking. (Followup to #1972)
=> Remove ending slash from ankiconnect ignore

ext/js/comm/anki-connect.js
In some areas we rely on this array to be the correct size. This can cause weird errors when a user is enabling or disabling Anki. It makes sense to say that notes cannot be added (false) if Anki is disabled when this gets called.
=> Return array filled with false in canAddNotes if Anki is disabled

ext/js/pages/settings/profile-controller.js, ext/templates-modals.html, ext/templates-settings.html
Since adding profiles clones the settings of an existing profile, there's no reasonable way for a user to create a default profile or get one back to default without resetting all of their settings.
=> Add option to reset settings of individual profiles

ext/js/pages/settings/anki-deck-generator-controller.js, ext/templates-modals.html, types/ext/settings.d.ts
This was overlooked in #1930.
Adds support for kanji formats in note generator as well.
=> Allow selecting different flashcard formats in note generator

ext/js/language/language-descriptors.js, types/ext/language-descriptors.d.ts
The Hawaiian language generally the Latin alphabet with some other symbols like the Okina `ʻ` symbol.
I presume because it uses capitalisation, and that the dictionary forms also include Okina and the symbols that means there does not need to be much processing. I hope so, I will test the edge cases after it's merged in.
Basically, I presume Yomitan works by looking up text in the dictionary and displays it if it exists. Please correct me if I am wrong and if I need to write some sort of custom parser. 
So instead of going "Oh, this is English text, let's look it up in the dictionary" I am presuming Yomitan will look up anything it hovers over in the dictionary, and if it matches it will display it regardless of alphabet.
Example text:
```
ʻōlelo
```
Please note Hawaiian only has a 3 …
=> Add Hawaiian language support

ext/js/dom/text-source-element.js, ext/js/language/text-scanner.js
Somewhat fixes #1946
The `scan-disable` class or any other classes that get tossed into the excludes at some point cause `content` to shrink when running `_constrainTextSource` over them. But `fullContent` does not shrink. `fullContent` cannot be used in the `this._isTextLookupWorthy` check to determine whether to show an empty popup.
=> Fix `scan-disable` being bypassed for some elements

ext/js/display/display.js, ext/js/display/query-parser.js, ext/js/language/text-scanner.js
1. `options.scanning.enableOnSearchPage` was never properly checked for. It was checked for in `_updateNestedFrontend` but the disable is promptly overwritten.
2. `query-parser.js` `setOptions` calls `this._textScanner.setEnabled(true);` right before it is also called by its parent `display.js` `_updateContentTextScanner`. The value it sets is also immediately overwritten.
This is the only time that function is ever called, limiting its use solely to confuse me in figuring out this bug. So I've removed it.
3. Who in the world wrote this: `[...args]`.
=> Fix disabled scanning on search page not disabling for touch

ext/js/data/database.js
Addresses https://github.com/yomidevs/yomitan/issues/1847#issuecomment-2924122150
If the database gets into a state where there are no object stores, there is also no data present and it is safe to delete the database to recover. It may not be safe to delete the database in other situations, so the user will be presented with a more descriptive error instead if it hits a transaction failure.
Transaction failures seem to be almost always caused by a missing object store and would be an unrecoverable state even if only a single one is missing but there is no evidence of such cases occurring and I currently do not like the idea of potentially bulldozing user data for recovery. In a database corruption with missing object stores it is still technically possible for the user to manually …
=> Better bad transaction error and auto reset database from unrecoverable state

README.md, package.json
Updating this often gets overlooked and it certainly is not getting updated every time we update dependencies so I've removed the version numbers from this.
=> Update readme package list and remove version numbers

ext/js/pages/settings/profile-controller.js
Duplicating or adding a new profile does not change the profile to the new profile. It always adds onto the end of the list. It will never need to set the currently active profile index.
Setting the profile here causes a desync of the active profile which causes other functions to request the wrong profile index when trying to get the current profile. Deleting this profile after adding it causes index out of range errors.
Likely missed this when implementing #1983.
=> Fix profile delete causing errors fetching current profile

ext/js/comm/yomitan-api.js, ext/js/display/display-generator.js, ext/js/display/pronunciation-generator.js, ext/js/display/structured-content-generator.js, ext/js/dom/css-style-applier.js, ext/js/templates/anki-template-renderer.js, ext/js/templates/template-renderer-frame-main.js, test/fixtures/anki-template-renderer-test.js, test/utilities/anki.js
1. Previously the api passed through `domlessDocument` but it looks like we also need `domlessWindow` since a few parts of structured content generation use `window`
2. `linkedom` uses `css-select` for its css handling. There are some css selectors this doesn't support and so the api currently won't be able to support these. These selectors are now skipped and logged instead of erroring.
3. The pronunciation generator that renders all of the pitch accent stuff heavily relies on document and was just a collection of functions making this very messy to do. I've converted it to a class to avoid the mess of passing document into every single function and it now gets `domlessDocument` from the api.
=> Prevent api glossary and pitch handlebars generation from breaking

PRIVACY-POLICY.md
For anyone outside the team reading this, Firefox now requires extensions that send data outside the extension to have a privacy policy. Regardless of whether the extension directly exports user data to the extension owners or profits from user data (which Yomitan does not).
This does not indicate any change in Yomitan.
=> Add privacy policy file

ext/js/templates/template-renderer-media-provider.js
Newlines in html are ignored so they need to be <br> tags for Anki.
This mainly applies to `clipboardText` and `popupSelectionText`. Other string media such as `textFurigana` shouldn't have newlines.
=> Re-inflate newlines in media for Anki when rendering templates

ext/js/display/search-display-controller.js
IME composition commit, typically performed by pressing the Enter key, is used to finalise user input into raw text for the consumer application, which is Yomitan in this case.
On certain OS/browser/IME combinations, such as Debian Linux with Firefox/Chromium and Fcitx with Mozc the browser may emit keydown event before the actual IME composition state is updated by the browser. This means that checking solely for the isComposing state is not a reliable method in all environments.
Mozilla recommends ignoring all events with keycode 229, which is a special value used for IME-processed events. With this change proper operation is observed on both Firefox and Chromium on the same Debian setup that reproduced the issue.
https://developer.mozilla.org/en-US/docs/Web/API/Element/keydown_event#key …
=> search: fix IME composition commit triggering search

PRIVACY-POLICY.md, ext/settings.html, ext/welcome.html
Mostly addresses the latest things mozilla is not happy with us about.
This is maybe missing at the moment: "If data collection starts or changes in an add-on update, or the consent and control is introduced in an update, it must be shown to all new and upgrading users."
We aren't introducing "consent and control" in this update and any handling of data is not changing. But I'm not sure the rabid privacy hounds at mozilla will see it this way. They may just want to take another bite at the billion dollar megacorp Yomitan because of the addition of the audio toggle on the welcome page possibly being seen as "consent and control is introduced".
=> Note potential data being sent on settings and add audio toggle to welcome page

ext/css/settings.css, ext/js/pages/settings/anki-deck-generator-controller.js, ext/templates-modals.html
Fixes #1637
This gets asked for sometimes since migaku has a similar feature. The idea being that the user can copy/paste a block of text into the note generator, parse it, dedupe it, and generate cards.
=> Add options to parse and dedupe input for the Anki Note Generator

ext/js/background/backend.js, ext/js/comm/yomitan-api.js, ext/js/core/utilities.js, ext/js/data/anki-note-builder.js, ext/js/data/anki-note-data-creator.js, ext/js/data/anki-util.js, ext/js/display/display.js, ext/js/pages/settings/anki-deck-generator-controller.js, types/ext/yomitan-api.d.ts
**This is a breaking change.** Previously, `ankiFields` returned an array of fields matching what was requested. This makes it unreasonable to include any extra data. Considering the API is still rather new it seems silly to add in jank to preserve compatibility. The new structure is:
```json
{
"fields": [],
"dictionaryMedia": [],
"audioMedia": []
}
```
Users migrating from the old format will simply have to access the `fields` field instead of accessing the returned json object directly. Full documentation on the new format is here https://github.com/Kuuuube/yomitan-api/pull/2.
A few notes on these changes:
1. `addScopeToCssLegacy` has been removed due to causing issues with the api's domless requirements. This was added as a workaround for Anki due to it shipping with an incredibly old …
=> Add media support to Yomitan API

ext/js/language/ja/japanese-wanakana.js, test/japanese-util.test.js
With `Automatic kana conversion` enabled on the search page lowercase romaji = hiragana and uppercase romaji = katakana.
`TTU` should convert to `ッツ`. And it does but not when typed one character at a time.
The intermediate steps as each character is typed being:
`T` -> `T`
`TT` -> `ッT` (This was being incorrectly converted to `ッt`)
`ッTU` -> `ッツ`
Same goes for all the sokuon conversions.
=> Preserve uppercase when converting romaji to katakana using uppercase romaji

ext/js/display/display-generator.js, ext/js/display/structured-content-generator.js, ext/js/language/text-utilities.js
Fixes #2101
For the most part there are no issues with language tags being set (fixed in #979) but `getLanguageFromText` falls back to `ja` too easily. Most Chinese texts will cause `partiallyJapanese` to return `True` and likewise for Japanese texts on `isStringPartiallyChinese`.
Falling back to the user's selected language should be preferred in cases where `ja` cannot be confidently assigned. Ideally all dictionaries would have source and target languages defined but that is not the case.
This preserves the behavior of properly assigning the `ja` language to glossaries with the source language of `ja` but target language of something else. For example an `en` -> `ja` dictionary has a `ja` glossary but the user will need their language set to `en`. While also not incorrectly assigning …
=> Make getLanguageFromText more accurate and mostly avoid conflict with Japanese, Chinese, Cantonese

ext/data/schemas/options-schema.json, ext/js/data/options-util.js, ext/settings.html, test/options-util.test.js
Apparently `8766` collides with asbplayer. With the great help of a random number generator, I have gotten port 19633. As far as I can tell nothing uses this.
Companion PR on the API repo https://github.com/Kuuuube/yomitan-api/pull/6.
This change in Yomitan doesn't matter at all for accessing the API. All it controls is the default field set for the test button.
=> Change default Yomitan API port to 19633

ext/css/visibility-modifiers.css, ext/js/language/ja/japanese.js, ext/js/language/ko/korean.js, ext/js/language/translator.js, ext/settings.html
Fixes #1833 by adding Korean to the "Search text with non-Japanese, Chinese, or Cantonese characters" setting. Source I used for the codepoints is https://en.wikipedia.org/wiki/Hangul#Unicode
Also refactored japanese.js codepoint ranges to use CJK-util.js ranges
=> Add Korean to "Search text with non-Japanese, Chinese, or Cantonese characters" setting

CONTRIBUTING.md, ext/js/comm/yomitan-api.js
For my issue #2104.
Added a short loading builds instructions for firefox and edge browsers on the CONTRIBUTING to go along with Chrome. Tried to keep it very similar to the loading Chrome build section.
=> Added loading builds instructions for firefox and edge on CONTRIBUTING

ext/js/comm/yomitan-api.js, ext/js/data/anki-note-builder.js
Fixes #2111 
~It allows the user to turn on a toggle to~ uses the selected dictionary terms reading for all occurrences of the term within the parsed text.
This override is applied only to term definitions using the internal Yomitan text parser. It does not affect:
1. Kanji definitions
2. Entries parsed using the MeCab text parser
3. Furigana creation outside of the context of an Anki note
=> Use term reading for all occurences in sentence furigana

ext/data/schemas/options-schema.json, ext/js/background/backend.js, ext/js/comm/yomitan-api.js, ext/js/data/anki-note-builder.js, ext/js/data/options-util.js, ext/js/display/display-anki.js, ext/js/display/display-audio.js, ext/js/media/audio-downloader.js, ext/templates-modals.html, test/options-util.test.js, types/ext/anki-note-builder.d.ts, types/ext/display-audio.d.ts, types/ext/settings.d.ts
Fixes #2096
Although somewhat intentional... regression caused by #1152.
Not exposing options to individually turn each source on/off. It's extremely easy for users to disable default sources and add back the ones they want. And having a toggle for all of them at once avoids any issues with how to handle different languages having different audio sources assigned to them.
=> Allow disabling default audio sources

ext/js/data/anki-note-data-creator.js
Previously `compact` was allowed to do this as well. This creates a split between structured and non structured dicts where structured required `compact-popup-anki` but non structured would be compacted with either `compact` or `compact-popup-anki`.
=> Only allow glossaryLayoutMode 'compact-popup-anki' to trigger compact glossaries for non structured content dicts

ext/css/settings.css, ext/data/schemas/options-schema.json, ext/js/data/options-util.js, ext/js/pages/settings/data-transmission-consent-controller.js, ext/js/pages/settings/modal.js, ext/js/pages/settings/settings-display-controller.js, ext/js/pages/welcome-main.js, ext/templates-modals.html, ext/welcome.html, test/options-util.test.js, types/ext/settings.d.ts
Only shows on Firefox so test on Firefox or manually edit the HTML to show it on Chromium browsers.
Using a global setting for checking if it has been shown instead of a profile setting. Seems pointless to do this per profile.
=> Add data transmission consent modal for firefox

ext/templates-modals.html
Addresses issue #1124. Let me know if I should fix the description. 
On a side note, I've noticed that every time I use the flags to trigger profile change upon copying to clipboard, the search window always displays the profile that is set as the default as the profile in the search window. 
Example: I have the Clipboard and No Clipboard profiles. Clipboard has the Flag condition for when "clipboard" is included as a tag. No Clipboard is set as the default profile. Upon copying text the search window is created, and No Clipboard will be displayed as the profile in use because it is the default profile even though Clipboard's settings are used. It's pretty minor, though.
Also in https://github.com/FooSoft/yomichan/issues/1504#issuecomment-793132798 , it's mentioned to use the `\s+` regex …
=> Clarify usage of Flags type in Profile Conditions

ext/js/data/anki-note-data-creator.js, ext/js/dictionary/dictionary-data-util.js, types/ext/dictionary.d.ts
Fixes #2128
Some dicts were getting counted twice. Not worth fixing when the existing Anki implementation works properly.
Just added filtering for headword index since the popup needs to differentiate between frequencies when there are multiple headwords present which happens with certain term grouping settings:
This rips out most of the code added by #1479.
=> Remove separate handling for avg freq in popup and combine with Anki handling

ext/data/schemas/options-schema.json, ext/js/app/frontend.js, ext/js/data/options-util.js, ext/js/display/display.js, ext/js/language/text-scanner.js, ext/templates-modals.html, test/options-util.test.js, types/ext/settings.d.ts, types/ext/text-scanner.d.ts
As pointed out in https://github.com/yomidevs/yomitan/issues/2152, currently a middle mouse click still opens links in a new tab, and mouse button 4 and 5 are unusable since they trigger history back/forward. This blocks the new tab action if the appropriate toggles are selected and adds a new set of toggles for button 4/5. I tested all of this on Chrome.
=> Improve mouse input action prevention

ext/js/pages/settings/anki-controller.js
1. Prevents deleting all card formats, the delete button is set to disabled if there are 1 or less formats. The button listener also rejects all events if there are 1 or less formats.
2. If the user already has 0 card formats, prevents erroring in an unrecoverable way. The user will still be able to add back formats and recover without having to reset settings.
3. No longer error when deleting the first card format due to an invalid index. `-1` is not an acceptable index so it is set to `0` if `-1` occurs.
=> Fix anki flashcard format errors on deleting too many

ext/data/schemas/options-schema.json, ext/js/display/display.js, ext/settings.html, test/options-util.test.js, types/ext/settings.d.ts
This was suggested on Discord and I thought it'd be pretty cool. Especially useful on ereaders and would make scrolling through definitions on higher quality modes feel a lot better.
It doesn't exactly scroll by popup height, there is a small overlap to kind of help with orientation.
I wasn't sure where to place the checkbox, so it's currently under "Popup Behaviour" as an advanced option.
https://github.com/user-attachments/assets/92bf0d4f-fd18-4729-855d-5307a7df0f4d
=> Add "Reduced motion scrolling" option

ext/js/dictionary/dictionary-data-util.js
As discussed on discord, this merge request fixes the logic in the isNonNounVerbOrAdjective function, so that it doesn't treat every suru verb as a noun.
I have chosen to leave the 'n' logic in place. If a dictionary doesn't make use of the 'n' tag (such as Jitendex), then this function will simply return true if the word inflects, which appears to be the intended behavior.
If there are dictionaries that do make use of the 'n' tag, then this function will return false if the word can be treated as a noun. For instance, if a dictionary marks the word 勉強 as both a noun 'n' and a suru verb 'vs', then it should return false, which is also the intended behavior. (Jitendex also returns false for 勉強, since it doesn't provide any tag).
=> Fixing the logic in isNonNounVerbOrAdjective

ext/js/language/el/modern-greek-processors.js, ext/js/language/language-descriptors.js, test/language/modern-greek-processors.test.js, types/ext/language-descriptors.d.ts
Closes #2007
Adds a processor to convert double acute-accented words to their normalized, single-accented version, in order to properly appear in the dictionary. Without this, words like `πρόσωπό` will not show, no matter the dictionary.
It was [noted](https://github.com/yomidevs/yomitan/issues/2007#issuecomment-2879341866) in the issue above, that the same could be achieved via removing diacritics altogether and modifying the dictionary. I didn't manage to make that approach work.
I still think this is a plain improvement over the current version and can not picture any drawbacks. Let me know if you have any feedback and I will happily iterate over it.
=> [el] Add processor to support double acute-accented words
