- .github/workflows/ci.yml
Some minor aesthetic and version updates, and also explicit definition of permissions to satisfy https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
> Format ci.yml, update to checkout@v3, and restrict permissions to satisfy OSSF scorecard

- ext/settings.html
This borrows from Rikaichan's renaming, and added a few more changes that wasn't made in the commit for some reason (changing the kana, and linking to the README instead of foosoft.net).
~~This is currently a draft simply because I want to build the extension and do a quick smoke test first.~~
P.S. I noticed in https://github.com/themoeway/zero-epwing-go/pull/2 that you may prefer squashed commits. I think the commits here make sense, but let me know if you want me to squash all the commits into one. If this is the case, I suggest editing the [contributing page](https://github.com/themoeway/yomitan/blob/master/CONTRIBUTING.md) with the aforementioned info.
> Rename Yomichan -> Yomitan in settings page

- dev/data/manifest-variants.json
A PR submitted on behalf of @djahandarie while he works on playwright
> fix: properly removed service worker and re-added background.html to Firefox

- ext/js/background/backend.js
Fixes #112. However, this is pretty much a band-aid fix for one small problem. We might want to look further into #114 to see if there is a better way of fixing the non-persistent extension issue overall.
> fix: welcome page no longer loads multiple times

- README.md
Hi, I noticed a small error in the readme.
> Fix minor mistake in README.md

- .github/workflows/playwright.yml
This pr removes the previous font package and adds Noto Sans JP from the Google fonts repository. Tested on a fork and works fine.
> Fix issue with Playwright where font wouldn't load or would load incorrectly

- .github/workflows/create-prerelease-on-tag.yml
Fix a bug introduced in #247 that caused the archive files to not get properly built in CI
> Fix bug in prerelease CI workflow

- dev/data/manifest-variants.json
> Bump minimum Firefox version to 115 for storage.session support

- .github/workflows/publish-firefox-development.yml
Minor error that was preventing the update extension from actually going out for Firefox.
> Fix CI/CD errors

- .github/workflows/publish-firefox-development.yml
Generate a proper version number for Firefox `updates.json`
> Fix version number in Firefox updates.json in CD

- README.md
This also adds ToC entries for the readme changes in https://github.com/themoeway/yomitan/pull/276.
> Replace References to Yomichan Import

- .github/workflows/playwright.yml
Job-level environment variable so it works on both PR/merge
> Playwright GH action env push fix

- README.md
Capitalizes an instance of "yomichan" in the README.
> Capitalize Yomichan in README

- .eslintrc.json
- ext/js/background/backend.js
- ext/js/background/offscreen-proxy.js
- ext/js/background/offscreen.js
combining #316, #319 - specifically the text replacement fix
> Move DB into offscreen (on Chrome) to avoid lookup delays caused by service worker startup lag

- .github/workflows/publish-chrome.yml
- dev/data/manifest-variants.json
Needed to make some minor changes to make sure it is actually releasable on stable.
> Update stable CI/CD workflow and stable extension ID in preparation for release

- README.md
> Link to stable extension in Chrome Web Store and Firefox Addons in README.md

- dev/build-libs.js
- ext/data/schemas/dictionary-kanji-bank-v1-schema.json
- ext/data/schemas/dictionary-kanji-bank-v3-schema.json
- ext/data/schemas/dictionary-kanji-meta-bank-v3-schema.json
- ext/data/schemas/dictionary-tag-bank-v3-schema.json
- ext/data/schemas/dictionary-term-bank-v1-schema.json
- ext/data/schemas/dictionary-term-bank-v3-schema.json
- ext/data/schemas/dictionary-term-meta-bank-v3-schema.json
- ext/data/schemas/options-schema.json
Fixes some warnings that the AJV compiler generates when running build-libs.js.
> Fix issues in build-libs

- docs/templates.md
- ext/settings.html
- test/data/html/test-document1.html
Replace all occurrences of よみちゃん / ヨミチャン with よみたん / ヨミタン
> Replace all occurrences of よみちゃん / ヨミチャン with よみたん / ヨミタン

- ext/js/pages/settings/dictionary-controller.js
Allow some elements to be null.
> Fix welcome page not having certain elements

- ext/js/app/content-script-main.js
- ext/js/background/background-main.js
- ext/js/background/offscreen-main.js
- ext/js/core.js
- ext/js/display/popup-main.js
- ext/js/display/search-main.js
- ext/js/language/dictionary-worker-main.js
- ext/js/language/sandbox/japanese-util.js
- ext/js/pages/action-popup-main.js
- ext/js/pages/generic-page-main.js
- ext/js/pages/info-main.js
- ext/js/pages/permissions-main.js
- ext/js/pages/settings/popup-preview-frame-main.js
- ext/js/pages/settings/settings-main.js
- ext/js/pages/welcome-main.js
- ext/js/templates/sandbox/template-renderer-frame-main.js
- jsconfig.json
This change removes most of the IIFEs, which originally existed to provide scope isolation. Since modules are used, scope isolation is no longer needed.
Main functions have also had this change applied, and most of the main functions are awaited, since top-level await is available in these contexts for the browser versions this extension targets. Top-level await does not work in background-main.js.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await#browser_compatibility
> IIFE updates

- dev/generate-css-json.js
I missed this comment somehow in #387 .
> fix wrong JSDoc comment

- .eslintrc.json
- ext/js/pages/settings/profile-conditions-ui.js
- ext/js/pages/settings/translation-text-replacements-controller.js
https://github.com/themoeway/yomitan/pull/402#pullrequestreview-1790202985
> Enable no-new eslint rule

- ext/js/accessibility/google-docs.js
- ext/js/background/backend.js
- ext/js/comm/api.js
- ext/js/display/query-parser.js
- types/ext/api.d.ts
> API type safety

- ext/js/app/frontend.js
- ext/js/background/backend.js
- ext/js/comm/api.js
- types/ext/api.d.ts
First step towards fixing some google docs stuff.
#235; #451
> Google docs fixes

- ext/data/schemas/dictionary-term-meta-bank-v3-schema.json
Not sure why it was like this.
> Remove unnecessary array

- ext/js/app/popup-proxy.js
- ext/js/app/popup-window.js
- ext/js/app/popup.js
- ext/js/display/display-audio.js
- ext/js/display/display.js
- types/ext/display.d.ts
Another step towards improved API safety where serialized messaging is used.
> Display API safety

- .eslintrc.json
- ext/js/core/json.js
> Add eslint rule no-restricted-syntax

- ext/js/app/frontend.js
- ext/js/app/popup-factory.js
- ext/js/app/popup-proxy.js
- ext/js/app/popup-window.js
- ext/js/app/popup.js
- ext/js/comm/cross-frame-api.js
- ext/js/comm/frame-ancestry-handler.js
- ext/js/comm/frame-offset-forwarder.js
- ext/js/core.js
- ext/js/display/display-resizer.js
- ext/js/display/display.js
- ext/js/input/hotkey-handler.js
- types/ext/core.d.ts
- types/ext/cross-frame-api.d.ts
- types/ext/display.d.ts
- types/ext/frame-ancestry-handler.d.ts
- types/ext/frontend.d.ts
This change makes the final update for better API safety for cross frame messaging.
> Cross frame API safety

- test/data/html/document-util.html
- test/document-util.test.js
- types/test/document-util.d.ts
> document-util to use JSON attribute instead of multiple data-* attributes

- ext/js/app/frontend.js
- ext/js/background/backend.js
- ext/js/core.js
- ext/js/display/display.js
- ext/js/dom/dom-text-scanner.js
- ext/js/templates/sandbox/anki-template-renderer.js
- types/ext/backend.d.ts
- types/ext/dictionary-importer.d.ts
- types/ext/dom-text-scanner.d.ts
- types/ext/log.d.ts
- types/ext/text-scanner.d.ts
This change adds more types and refactors some existing ones.
> type updates

- ext/js/pages/settings/dictionary-controller.js
The manual move to index for dictionaries was having issues as mentioned in the discord. Was a small typecheck issue.
> Fix dictionary move to index

- .eslintrc.json
- ext/js/core/utilities.js
- ext/js/dom/sandbox/css-style-applier.js
- ext/js/language/sandbox/japanese-util.js
- package-lock.json
- package.json
- test/cache-map.test.js
- test/deinflector.test.js
- test/fixtures/anki-template-renderer-test.js
- test/hotkey-util.test.js
- test/json-schema.test.js
- test/options-util.test.js
- test/profile-conditions-util.test.js
Pretty simple. As I was about to make some other changes, I noticed there were some unneeded eslint disables.
> Remove unneeded eslint disables

- ext/js/extension/web-extension.js
Fixes https://github.com/themoeway/yomitan/pull/551#issuecomment-1915860425
> Fix chrome.runtime.lastError not working properly on Firefox

- test/dictionary-data.write.js
Fixes the issue mentioned here: https://github.com/themoeway/yomitan/pull/600#issuecomment-1920454391
> Fix dictionary data write

- test/data/translator-test-inputs.json
- test/dictionary-data.test.js
- test/dictionary-data.write.js
- test/utilities/translator.js
- types/ext/translation.d.ts
- types/test/translator.d.ts
Resolves a TODO I added in the code about some unsafe type assumptions.
> Improve translator test inputs typing

- .eslintrc.json
- ext/js/background/backend.js
- ext/js/comm/clipboard-monitor.js
- ext/js/data/anki-note-builder.js
- ext/js/data/sandbox/anki-note-data-creator.js
- ext/js/display/display-generator.js
- ext/js/display/query-parser.js
- ext/js/display/sandbox/pronunciation-generator.js
- ext/js/display/sandbox/structured-content-generator.js
- ext/js/language/ja/japanese-wanakana.js
- ext/js/language/ja/japanese.js
- ext/js/language/translator.js
- ext/js/media/audio-downloader.js
- ext/js/templates/sandbox/anki-template-renderer.js
- test/japanese-util.test.js
> Move Japanese files to own subfolder

- benches/language-transformer.bench.js
Add one more bench and add `n=[number of test cases]` to the test name.
> Bench updates

- test/handlebars.test.js
Tests a bug in the [kbn-handlebars](https://github.com/elastic/kibana/tree/main/packages/kbn-handlebars) implementation.
> Test handlebars

- benches/dictionary-data.bench.js
- benches/jsconfig.json
- benches/translator.bench.js
- test/fixtures/translator-test.js
Creates some benchmarks for some translator functions. See https://github.com/themoeway/yomitan/pull/584#issuecomment-1930453829
> Add benchmarks for Translator class methods

- docs/anki-integration.md
- ext/settings.html
> Add cloze-body-kana docs

- docs/anki-integration.md
- ext/settings.html
> Add pitch-accent-categories documentation

- ext/js/application.js
- ext/js/dom/style-util.js
- ext/js/extension/web-extension.js
Moving just because it makes more sense in the WebExtension class.
> Move isExtensionUrl into WebExtension

- ext/js/background/offscreen-proxy.js
> Document OffscreenProxy

- dev/manifest-util.js
structuredClone is available in node scripts.
> Simplify custom clone function

- ext/settings.html
- ext/welcome.html
> fix dictionary details on welcome page 

- docs/anki-integration.md
- ext/settings.html
> add documentation for {phonetic-transcriptions}

- test/cache-map.test.js
- test/core.test.js
- test/css-json.test.js
- test/hotkey-util.test.js
- test/japanese-util.test.js
- test/json-schema.test.js
- test/language-transformer.test.js
- test/object-property-accessor.test.js
- test/options-util.test.js
- test/profile-conditions-util.test.js
- test/text-source-map.test.js
> Make vitests idiomatic

- ext/js/accessibility/google-docs-util.js
- ext/js/app/frontend.js
- ext/js/app/popup.js
- ext/js/dom/document-util.js
- ext/js/dom/dom-data-binder.js
- ext/js/dom/text-source-element.js
- ext/js/dom/text-source-generator.js
- ext/js/dom/text-source-range.js
- ext/js/input/hotkey-handler.js
- ext/js/language/text-scanner.js
- ext/js/pages/settings/generic-setting-controller.js
- ext/js/pages/settings/keyboard-mouse-input-field.js
- ext/js/pages/settings/keyboard-shortcuts-controller.js
- ext/js/pages/settings/nested-popups-controller.js
- ext/js/pages/settings/profile-conditions-ui.js
- ext/js/pages/settings/scan-inputs-controller.js
- ext/js/pages/settings/settings-display-controller.js
Converts class to a module, resolving a TODO and an error suppression.
> Refactor DocumentUtil

- dev/bin/build.js
- dev/util.js
> Remove testMain

- .lycheeignore
- README.md
Should hopefully fix #702.
I'm assuming this is failing because Google has some sort of anti-robot filter that is causing them to fail, or they just can't handle the redirects properly.
> Add ignore links

- .eslintrc.json
- ext/js/background/backend.js
- ext/js/data/database.js
- ext/js/data/options-util.js
- ext/js/dictionary/dictionary-importer.js
- ext/js/display/display-anki.js
- ext/js/display/display-history.js
- ext/js/display/display.js
- ext/js/dom/text-source-generator.js
- ext/js/general/regex-util.js
- ext/js/input/hotkey-help-controller.js
- ext/js/language/translator.js
- ext/js/media/audio-downloader.js
- ext/js/pages/settings/dictionary-controller.js
- ext/js/templates/sandbox/anki-template-renderer.js
- test/document-util.test.js
- test/dom-text-scanner.test.js
- test/eslint-config.test.js
- types/ext/template-renderer.d.ts
- types/test/eslint-config.d.ts
Updates several instances of unsafe `any` being used.
> Turn on @typescript-eslint/no-unsafe-argument

- ext/js/pages/settings/dictionary-import-controller.js
> enable new dicts only on edited profile

- ext/js/language/language-descriptors.js
- types/ext/language-descriptors.d.ts
There's been some talk on discord about Turkish, so here it is.
> add turkish

- ext/js/comm/anki-connect.js
- test/playwright/playwright-util.js
This should fix the [playwright job that's been failing](https://github.com/themoeway/yomitan/actions/runs/8325702401/job/22779869838) on master since #693
> fix playwright failing on master

- ext/js/display/display-anki.js
> Prevent logging error when anki is disconnected

- .eslintrc.json
- ext/js/language/language-descriptors.js
> start using german deinflections

- docs/anki-integration.md
- ext/data/schemas/options-schema.json
- ext/js/data/options-util.js
- ext/js/display/display-anki.js
- ext/settings.html
- test/options-util.test.js
- types/ext/settings.d.ts
This is to fix #826, and a first step towards #578.
> add duplicate behavior dropdown

- ext/css/display.css
- ext/data/schemas/options-schema.json
- ext/settings.html
- types/ext/settings.d.ts
Requested in TMW discord. Not sure why we didn't have this option before.
> Add option to disable furigana and reading in Term display style

- ext/js/display/display-anki.js
Fixes #813
Fixes #878
Turns out this issue was not fully fixed by #843
> Prevent updating dict entry details for anki when anki is disabled

- .github/workflows/playwright_comment.yml
Resolves #910 
Tested in my branch, just needed to add `update-only: true` to the rule.
> Restore Playwright Success Comments on Update

- ext/settings.html
> Add permissions page link in settings

- ext/js/language/translator.js
> fix search resolution infinite loop

- ext/js/language/translator.js
- test/data/anki-note-builder-test-results.json
- test/data/translator-test-inputs.json
- test/data/translator-test-results-note-data1.json
- test/data/translator-test-results.json
> add test case for search resolution "word"

- ext/js/pages/settings/recommended-permissions-controller.js
- ext/welcome.html
Tested on Firefox and Chromium.
| ![image](https://github.com/themoeway/yomitan/assets/61125188/577cbb03-7b73-4ea6-8b3d-a1ac96b69ae5)  |  ![image](https://github.com/themoeway/yomitan/assets/61125188/f0b687b6-8198-419c-83af-4355232d3bd9) |
|---|---|
> Allow setting optional permissions on welcome page

- ext/js/language/language-descriptors.js
- types/ext/language-descriptors.d.ts
> Add Lao language

- .eslintrc.json
- ext/js/core/log.js
- ext/js/language/es/spanish-transforms.js
- ext/js/language/language-descriptors.js
- ext/js/language/language-transformer.js
- ext/js/language/language-transforms.js
- test/language/spanish-transforms.test.js
- types/ext/language-transformer-internal.d.ts
- types/ext/language-transformer.d.ts
Starting the spanish transforms work. ¡Vaya!
> Basic Spanish Transforms

- ext/settings.html
> demolished duplicate "adjust"

- ext/js/dom/text-source-range.js
> Fix semantics of disallowExpandSelection

- ext/js/pages/settings/languages-controller.js
This is my first contribution to yomitan.
Been a member of the server for a while and am willing to engage into improving the extension further.
Right now I am still learning about the extension's code.
This solves the #1054 issue.
> #1054 language sorting by name

- benches/canary.bench.js
> actually loop 1 through 100,000

- ext/css/display.css
This is to allow linebreaks in inflection descriptions with `\n`.
> allow linebreaks in notification

- .eslintrc.json
> Disable capitalized-comments

- ext/css/action-popup.css
- ext/css/material.css
- ext/css/popup-preview.css
- ext/css/settings.css
- ext/js/pages/action-popup-main.js
- ext/js/pages/info-main.js
- ext/js/pages/permissions-main.js
- ext/js/pages/quick-start-guide-main.js
- ext/js/pages/settings/popup-preview-frame.js
- ext/js/pages/settings/settings-display-controller.js
- ext/js/pages/settings/settings-main.js
- ext/js/pages/welcome-main.js
- ext/permissions.html
- ext/popup-preview.html
- ext/quick-start-guide.html
- ext/settings.html
- ext/welcome.html
> Add full dark mode support

- ext/action-popup.html
- ext/css/action-popup.css
- ext/js/pages/action-popup-main.js
As mentioned in https://github.com/themoeway/yomitan/pull/1088#issuecomment-2178741795
> Show loading message before action popup is loaded

- ext/css/display.css
- ext/css/search.css
- ext/search.html
Fixes  #1113
Tested on Firefox, Firefox Android, and Chromium.
| Not scrolled      | Scrolled down      |
|![image](https://github.com/themoeway/yomitan/assets/61125188/3d02c552-eec9-48cd-9a1f-928f5e87c6bd)|![image](https://github.com/themoeway/yomitan/assets/61125188/0a4c80bc-1f1c-490c-9651-d6c6ada8a1d3)|
> Make search header sticky

- ext/js/data/anki-note-builder.js
- ext/js/display/display-anki.js
- ext/js/pages/settings/anki-deck-generator-controller.js
- ext/js/pages/settings/anki-templates-controller.js
This also fixes a bug where cards wouldnt be rendered at all when using bulk card generation due to it hitting an error.
> Support dictionaryStylesMap in anki-deck-generator-controller and anki-templates-controller

- docs/dictionaries.md
> Remove vestigial EPWING image reference

- ext/js/language/ja/japanese.js
> Add support for preprocessing halfwidth nakaguro

- ext/js/display/display.js
- types/ext/api.d.ts
> Attempt to fallback on kanji or terms dict when no results are found in the other

- ext/js/language/language-descriptors.js
- types/ext/language-descriptors.d.ts
Add support for the Mongolian language to be selectable as a language.
> [mn] add Mongolian

- ext/css/display.css
- ext/templates-display.html
Fixes #1156 
| Before      | After      |
| ![image](https://github.com/themoeway/yomitan/assets/61125188/5337767f-3455-44ce-9566-ec58486933b0) | ![image](https://github.com/themoeway/yomitan/assets/61125188/f00b74cc-1350-42df-ac5a-6fbbcc604634) |
| ![image](https://github.com/themoeway/yomitan/assets/61125188/caf6b04f-c376-4576-ba3c-f9505388b9f9) | ![image](https://github.com/themoeway/yomitan/assets/61125188/239b3c36-5a26-4207-af40-646c9004c381) |
> Fix dark/light mode footer message box colors

- ext/data/schemas/options-schema.json
- ext/js/app/frontend.js
- ext/js/data/options-util.js
- ext/js/display/display.js
- ext/js/language/text-scanner.js
- ext/settings.html
- test/options-util.test.js
- types/ext/settings.d.ts
- types/ext/text-scanner.d.ts
> Add Option for Scanning Alt Text

- ext/js/language/translator.js
> fix comment

- ext/css/search-settings.css
- ext/css/search.css
- ext/js/display/search-display-controller.js
- ext/js/display/search-main.js
- ext/search.html
|     |       |
| ![image](https://github.com/themoeway/yomitan/assets/61125188/6ae70f60-d429-4f8d-aede-01868b2d9c8d) | ![image](https://github.com/themoeway/yomitan/assets/61125188/430b788b-a68c-4530-8e97-eb663a81b5c9) |
Open to suggestions for the ui. Moving the cog to the right isnt reasonable since mobile users are likely to accidentally click it when trying to search.
> Add search settings modal

- ext/action-popup.html
- ext/js/display/search-display-controller.js
- ext/js/pages/action-popup-main.js
- ext/js/pages/generic-page-main.js
- ext/js/pages/info-main.js
- ext/search.html
- ext/settings.html
#1123
- Rename "primary profile" to "default profile"
> Standardize references to current profile

- ext/js/language/language-descriptors.js
- types/ext/language-descriptors.d.ts
In accordance to https://github.com/themoeway/kaikki-to-yomitan/issues/105
> Add Tagalog

- ext/js/language/text-scanner.js
> Clear cached mouse position on mouseout

- ext/js/pages/settings/dictionary-controller.js
- ext/js/pages/settings/popup-preview-controller.js
- ext/js/pages/settings/popup-preview-frame.js
- types/ext/popup-preview-frame.d.ts
- types/ext/settings-controller.d.ts
> When no dictionary is enabled, update preview after enable dictionary

- ext/js/language/language-descriptors.js
- types/ext/language-descriptors.d.ts
To match https://github.com/themoeway/kaikki-to-yomitan/pull/115
> [it] preprocess italian diacritics

- ext/js/language/en/english-transforms.js
- test/language/english-transforms.test.js
> [en] add -able deinflection rule

- ext/data/schemas/options-schema.json
- ext/js/app/frontend.js
- ext/js/data/options-util.js
- ext/js/display/display.js
- ext/js/language/text-scanner.js
- ext/settings.html
- test/options-util.test.js
- types/ext/settings.d.ts
- types/ext/text-scanner.d.ts
Wanted to avoid adding an option for this (most complaints requesting it were just fixeable bugs) but we cant do anything about #1038.
Fixes #1038
> Add option for scan without mouse move

- ext/js/language/ja/japanese-transforms.js
- test/language/japanese-transforms.test.js
> [ja] add -nnee deinflection

- README.md
> update README to point to yomitan.wiki

- ext/js/language/language-descriptors.js
- types/ext/language-descriptors.d.ts
These have been requested and added on KTY but not yet in yomitan
> add cs, eo, lv, kn, uk

- .github/workflows/publish-edge.yml
- .github/workflows/release.yml
- dev/data/manifest-variants.json
> Add publish to Microsoft CI Github Action

- README.md
Adding this scorecard back in because I didn't realize it was useful 😅
> Add back openSSF scorecard

- ext/js/pages/settings/dictionary-controller.js
If there are no updates when checking for updates, disables the button.
> Disable no update button

- ext/js/language/language-descriptors.js
- types/ext/language-descriptors.d.ts
This will let users read Hindi.
> Add hindi language option.

- ext/info.html
It adds the microsoft edge link to ask for ratings and reviews as per the issue #1372 
Kindly Review the PR.
> added link of microsoft edge to ask for ratings and reviews

- .github/workflows/release.yml
Fixes this failure https://github.com/themoeway/yomitan/actions/runs/10672416515/job/29579847516#step:4:12
> Add GITHUB_TOKEN

- docs/supported-languages.md
- ext/js/language/language-descriptors.js
- types/ext/language-descriptors.d.ts
This adds support for looking up words in Danish.
> Support looking up Danish

- ext/js/media/media-util.js
> Add support for AVIF

- ext/data/recommended-dictionaries.json
##issue #1331 
last timeline(#1400 ) got twisted up. Added non ja recommended dictionaries, just terms dictionary.
> added recommended dictionaries for non JA languages

- ext/data/schemas/options-schema.json
> Make layoutAwareScan `true` by default

- ext/js/pages/settings/dictionary-controller.js
Enqueue the dictionary delete into a queue after confirm delete, then disable the delete button.
Fixes #1409
> Dictionary delete queue

- ext/settings.html
> Puts custom font-family setting in advanced

- ext/js/pages/settings/dictionary-controller.js
> Apply custom dict css when resetting settings

- README.md
> Update discords invite links

- README.md
- docs/development/language-features.md
- package-lock.json
Theres also `auto-approve-run.yml` with the tmw bot and we have tmw in the manifest but I assume those cant be changed at the moment.
> Update remaining paths

- ext/js/language/ja/japanese-transforms.js
- test/language/japanese-transforms.test.js
> [ja] Add 恋う irregular verb

- ext/js/pages/settings/dictionary-import-controller.js
> Fix Visible Recommended Dictionary Headers

- ext/js/app/frontend.js
> Fix incorrect touch exclude selector

- .lycheeignore
This link has been failing in CI. Let's ignore it
> Add forbidden link

- .github/workflows/playwright_comment.yml
Fixes the if statement logic and combines the flaky/visual difference messages.
> Fix Flaky Test Comment

- test/playwright/integration.spec.js
Let's fail faster when playwright is in a pathological state loading dicts
> Change playwright dictionary loading timeout

- ext/js/display/display.js
- ext/js/display/query-parser.js
- ext/js/language/text-scanner.js
- types/ext/text-scanner.d.ts
Fixes #1564
Regression caused by #1538
> Restore searchOnClick for search page

- ext/js/language/text-scanner.js
Due to an incorrect merge conflict resolution this got messed up.
> Fix disabled scan resolution in ja, zh, yue, and ko

- README.md
Fixed Unclosed parentheses in README #1607
> Fixed issue #1607 updated reame removed typos

- ext/settings.html
> Link to Yomitan wiki anki setup

- .eslintrc.json
- ext/js/language/fr/french-text-preprocessors.js
- ext/js/language/language-descriptors.js
- types/ext/language-descriptors.d.ts
> [FR] add apostrophe preprocessor

- ext/js/display/display-generator.js
> Change messaging to dictionary size

- ext/css/action-popup.css
> Fix CSS selector for off

- tag.sh
> tag.sh: only fetch origin remote, auto-increment last digit if there is an existing tag

- ext/settings.html
> Move "Persistent storage" to advanced settings

- ext/settings.html
> Add a link to the search page in popup settings

- ext/action-popup.html
- ext/css/action-popup.css
**Light mode before/after**
**Dark mode before/after**
> Make action popup smaller

- ext/js/background/backend.js
> Fix constant error on firefox mobile from chrome.contextMenus

- .github/workflows/create-prerelease-on-tag.yml
- .github/workflows/publish-chrome-development.yml
> Add upload_url to publish-chrome-development action

- docs/development/npm-scripts.md
- package.json
Having worked on the structured content generation a bit, it is immensely annoying to have to dig up the exact command to run this thing every time.
> Add script for writing anki structured content css

- ext/js/language/language-descriptors.js
- types/ext/language-descriptors.d.ts
Add support for Estonian to be selectable as a language.
> [et] Add Estonian

- .github/workflows/playwright.yml
This is also required in addition to #1727
> Really fix playwright

- .github/workflows/playwright.yml
- .github/workflows/playwright_comment.yml
Another fix on top of #1728 / #1727 / #1720 
Tested as best as I could on my fork, but will still not know for sure if this works until the new screenshots get regenerated.
> Really fix playwright fr finally

- package-lock.json
- package.json
- shell.nix
https://nodejs.org/en/about/previous-releases
20 is now maintenance LTS, and 22 is active LTS.
> Update to node 22

- ext/css/display.css
- ext/css/structured-content.css
- ext/data/structured-content-style.json
> Add back content-visibility: auto and make image go upwards to not get cut off when on bottom of entry container

- ext/js/pages/settings/dictionary-import-controller.js
> Update dictionary will update dictionary CSS

- ext/data/recommended-dictionaries.json
- ext/data/recommended-settings.json
- ext/js/language/language-descriptors.js
- types/ext/language-descriptors.d.ts
Adds Norwegian Bokmål and Norwegian Nynorsk.
> add norwegian

- ext/data/recommended-dictionaries.json
* Assyrian Neo-Aramaic
* Arabic
* Maltese
> Add pronunciation dicts

- docs/development/language-features.md
- ext/js/language/es/spanish-transforms.js
- test/language/spanish-transforms.test.js
- types/ext/language-transformer.d.ts
- Participles 
- Reflexive verbs
Fixes #1787 #1563 #1757
> More spanish transforms

- ext/css/settings.css
- ext/data/schemas/options-schema.json
- ext/js/data/anki-note-builder.js
- ext/js/data/options-util.js
- ext/js/data/permissions-util.js
- ext/js/display/display-anki.js
- ext/js/pages/settings/anki-controller.js
- ext/js/pages/settings/anki-templates-controller.js
- ext/settings.html
- ext/templates-modals.html
- ext/templates-settings.html
- test/options-util.test.js
- test/playwright/integration.spec.js
- test/utilities/anki.js
- types/ext/anki-note-builder.d.ts
- types/ext/settings.d.ts
> add overwriting options to each field

- ext/js/language/grc/ancient-greek-processors.js
- ext/js/language/grc/ancient-greek-transforms.js
- ext/js/language/language-descriptors.js
- test/language/ancient-greek-processors.test.js
- test/language/ancient-greek-transforms.test.js
- types/ext/language-descriptors.d.ts
adds basic deinflection for Ancient Greek
> [grc] basic deinflection

- ext/js/data/options-util.js
- test/options-util.test.js
sorry i forgot
https://github.com/yomidevs/yomitan/pull/1479#pullrequestreview-2370147020
> edited options-util.js to include settings for average frequency, bumped version

- ext/js/language/ga/irish-transforms.js
- ext/js/language/language-descriptors.js
- test/language/irish-transforms.test.js
- types/ext/language-descriptors.d.ts
Add modern Irish option.
Also add basic deinflection for nouns
> add modern Irish option

- test/data/html/popup-tests.html
Since #1845 this should succeed.
> Remove expected fail from playwright shadow dom open label

- ext/css/settings.css
- ext/js/pages/settings/audio-controller.js
- ext/templates-modals.html
- ext/templates-settings.html
Fixes #861
Similar to the dictionary up and down arrow UI. `Move to...` button is also available on the kebab menu.
> Allow ordering audio sources

- ext/data/templates/anki-field-templates-upgrade-v63.handlebars
- ext/data/templates/default-anki-field-templates.handlebars
- ext/js/data/options-util.js
- test/data/anki-note-builder-test-results.json
- test/options-util.test.js
This makes it possible to customize the phonetic transcriptions on the anki side. Could maybe use more structure, such as separating transcriptions by dictionary, but this is about the minimum to be useful.
> make phonetic transcriptions handlebar css-selectable

- ext/permissions.html
- ext/settings.html
> Make wording of clipboard related things language agnostic

- eslint.config.js
- ext/js/pages/settings/backup-controller.js
- package-lock.json
- package.json
- test/language-transformer-cycles.test.js
Cleaned up https://github.com/yomidevs/yomitan/pull/1714 to remove conflicts
Did some basic testing on my Chrome browser
> Update user facing dependencies

- ext/search.html
Generally a nuisance for android users.
> Turn off autocapitalize on search textarea

- ext/js/language/ja/japanese-kana-romaji-dicts.js
> Fix handling of n' in romaji to kana

- ext/js/background/backend.js
Fixes #1838
AnkiConnect only uses the first field to determine whether a card is a duplicate.
In some quick testing, this lets Yomitan send anywhere from 10-100,000x less data for dupe checking depending on the number of dictionaries the user has and which handlebars they are using.
Simply passing around this volume of data isn't much issue on modern systems but it does cause considerable lag within AnkiConnect in some cases, leading to much higher latency for users.
> Cut out unnecessary fields when dupe checking to reduce AnkiConnect network latency

- ext/js/language/language-transformer.js
> update variable name

- ext/data/recommended-settings.json
> Recommended setting to disable single quotes as sentence terminators

- ext/js/background/backend.js
- ext/js/comm/api.js
- ext/js/comm/shared-worker-bridge.js
- ext/js/dictionary/dictionary-database.js
- ext/js/display/media-drawing-worker.js
Removed logs appearing in https://github.com/yomidevs/yomitan/actions/runs/13587142381/job/37984544342
> Removed unnecessary console logs

- ext/css/settings.css
- ext/js/pages/settings/backup-controller.js
- ext/settings.html
> Hide progress and error containers for import/export dictionary collection until used

- ext/js/background/backend.js
> Move omnibox init to _prepareInternal to avoid chance of duplicating

- ext/js/data/anki-util.js
- ext/js/display/display-anki.js
Notes that will obivously be invalid will just cause an error when the user tries to add them.
> Disable Anki add button if dupe check is disabled and note is invalid

- ext/data/recommended-settings.json
> Recommend resetting scanning.scanResolution and translation.searchResolution for ja, zh, yue

- docs/development/language-features.md
Hi folks, made a small docs change to talk about adding recommended dicts to your language.
This is really quickly done, I will update the PR to point to a PR I'll make for hawaiian
> Update language-features.md to include rec dicts

- ext/js/display/display.js
Regression introduced in #2027. The bug fixed in #2027 is still fixed.
> Fix clicking search results searching the clicked on text

- ext/data/recommended-dictionaries.json
I added the wrong dict link, sorry!
> Update hawaiian dict link

- ext/data/recommended-dictionaries.json
OpenRussian is licenced under Creative Commons Attribution Share Alike 4.0 - https://github.com/Badestrand/russian-dictionary
> Add OpenRussian to recommended dictionaries for Russian

- ext/templates-modals.html
Kaikki now has a nice downloads page we can link to.
> Update kaikki link in recommended dictionaries

- ext/js/pages/settings/profile-controller.js
Regression probably caused by #1983
> Update settings page settings when profile is switched using action popup

- ext/js/language/ja/japanese-wanakana.js
- test/japanese-util.test.js
> Support capital N and NY for katakana in the special n handling

- ext/data/schemas/options-schema.json
- ext/js/app/frontend.js
- ext/js/data/options-util.js
- ext/js/display/display.js
- ext/js/language/text-scanner.js
- ext/templates-modals.html
- test/options-util.test.js
- types/ext/settings.d.ts
- types/ext/text-scanner.d.ts
Adds #2124 
Let me know if there are any questions or concerns
> Add option for preventing middle click action when hovering over text
